// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TerrainList.proto

package DnD.Terrain;

public final class TerrainListOuterClass {
  private TerrainListOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TerrainListOrBuilder extends
      // @@protoc_insertion_point(interface_extends:DnD.Terrain.TerrainList)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .Dnd.Terrain.Terrain terrains = 1;</code>
     */
    java.util.List<DnD.Terrain.TerrainOuterClass.Terrain> 
        getTerrainsList();
    /**
     * <code>repeated .Dnd.Terrain.Terrain terrains = 1;</code>
     */
    DnD.Terrain.TerrainOuterClass.Terrain getTerrains(int index);
    /**
     * <code>repeated .Dnd.Terrain.Terrain terrains = 1;</code>
     */
    int getTerrainsCount();
    /**
     * <code>repeated .Dnd.Terrain.Terrain terrains = 1;</code>
     */
    java.util.List<? extends DnD.Terrain.TerrainOuterClass.TerrainOrBuilder> 
        getTerrainsOrBuilderList();
    /**
     * <code>repeated .Dnd.Terrain.Terrain terrains = 1;</code>
     */
    DnD.Terrain.TerrainOuterClass.TerrainOrBuilder getTerrainsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code DnD.Terrain.TerrainList}
   */
  public  static final class TerrainList extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:DnD.Terrain.TerrainList)
      TerrainListOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TerrainList.newBuilder() to construct.
    private TerrainList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TerrainList() {
      terrains_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new TerrainList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private TerrainList(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                terrains_ = new java.util.ArrayList<DnD.Terrain.TerrainOuterClass.Terrain>();
                mutable_bitField0_ |= 0x00000001;
              }
              terrains_.add(
                  input.readMessage(DnD.Terrain.TerrainOuterClass.Terrain.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          terrains_ = java.util.Collections.unmodifiableList(terrains_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return DnD.Terrain.TerrainListOuterClass.internal_static_DnD_Terrain_TerrainList_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return DnD.Terrain.TerrainListOuterClass.internal_static_DnD_Terrain_TerrainList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              DnD.Terrain.TerrainListOuterClass.TerrainList.class, DnD.Terrain.TerrainListOuterClass.TerrainList.Builder.class);
    }

    public static final int TERRAINS_FIELD_NUMBER = 1;
    private java.util.List<DnD.Terrain.TerrainOuterClass.Terrain> terrains_;
    /**
     * <code>repeated .Dnd.Terrain.Terrain terrains = 1;</code>
     */
    public java.util.List<DnD.Terrain.TerrainOuterClass.Terrain> getTerrainsList() {
      return terrains_;
    }
    /**
     * <code>repeated .Dnd.Terrain.Terrain terrains = 1;</code>
     */
    public java.util.List<? extends DnD.Terrain.TerrainOuterClass.TerrainOrBuilder> 
        getTerrainsOrBuilderList() {
      return terrains_;
    }
    /**
     * <code>repeated .Dnd.Terrain.Terrain terrains = 1;</code>
     */
    public int getTerrainsCount() {
      return terrains_.size();
    }
    /**
     * <code>repeated .Dnd.Terrain.Terrain terrains = 1;</code>
     */
    public DnD.Terrain.TerrainOuterClass.Terrain getTerrains(int index) {
      return terrains_.get(index);
    }
    /**
     * <code>repeated .Dnd.Terrain.Terrain terrains = 1;</code>
     */
    public DnD.Terrain.TerrainOuterClass.TerrainOrBuilder getTerrainsOrBuilder(
        int index) {
      return terrains_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < terrains_.size(); i++) {
        output.writeMessage(1, terrains_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < terrains_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, terrains_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof DnD.Terrain.TerrainListOuterClass.TerrainList)) {
        return super.equals(obj);
      }
      DnD.Terrain.TerrainListOuterClass.TerrainList other = (DnD.Terrain.TerrainListOuterClass.TerrainList) obj;

      if (!getTerrainsList()
          .equals(other.getTerrainsList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getTerrainsCount() > 0) {
        hash = (37 * hash) + TERRAINS_FIELD_NUMBER;
        hash = (53 * hash) + getTerrainsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static DnD.Terrain.TerrainListOuterClass.TerrainList parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static DnD.Terrain.TerrainListOuterClass.TerrainList parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static DnD.Terrain.TerrainListOuterClass.TerrainList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static DnD.Terrain.TerrainListOuterClass.TerrainList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static DnD.Terrain.TerrainListOuterClass.TerrainList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static DnD.Terrain.TerrainListOuterClass.TerrainList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static DnD.Terrain.TerrainListOuterClass.TerrainList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static DnD.Terrain.TerrainListOuterClass.TerrainList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static DnD.Terrain.TerrainListOuterClass.TerrainList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static DnD.Terrain.TerrainListOuterClass.TerrainList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static DnD.Terrain.TerrainListOuterClass.TerrainList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static DnD.Terrain.TerrainListOuterClass.TerrainList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(DnD.Terrain.TerrainListOuterClass.TerrainList prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code DnD.Terrain.TerrainList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:DnD.Terrain.TerrainList)
        DnD.Terrain.TerrainListOuterClass.TerrainListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return DnD.Terrain.TerrainListOuterClass.internal_static_DnD_Terrain_TerrainList_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return DnD.Terrain.TerrainListOuterClass.internal_static_DnD_Terrain_TerrainList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                DnD.Terrain.TerrainListOuterClass.TerrainList.class, DnD.Terrain.TerrainListOuterClass.TerrainList.Builder.class);
      }

      // Construct using DnD.Terrain.TerrainListOuterClass.TerrainList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getTerrainsFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (terrainsBuilder_ == null) {
          terrains_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          terrainsBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return DnD.Terrain.TerrainListOuterClass.internal_static_DnD_Terrain_TerrainList_descriptor;
      }

      @java.lang.Override
      public DnD.Terrain.TerrainListOuterClass.TerrainList getDefaultInstanceForType() {
        return DnD.Terrain.TerrainListOuterClass.TerrainList.getDefaultInstance();
      }

      @java.lang.Override
      public DnD.Terrain.TerrainListOuterClass.TerrainList build() {
        DnD.Terrain.TerrainListOuterClass.TerrainList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public DnD.Terrain.TerrainListOuterClass.TerrainList buildPartial() {
        DnD.Terrain.TerrainListOuterClass.TerrainList result = new DnD.Terrain.TerrainListOuterClass.TerrainList(this);
        int from_bitField0_ = bitField0_;
        if (terrainsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            terrains_ = java.util.Collections.unmodifiableList(terrains_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.terrains_ = terrains_;
        } else {
          result.terrains_ = terrainsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof DnD.Terrain.TerrainListOuterClass.TerrainList) {
          return mergeFrom((DnD.Terrain.TerrainListOuterClass.TerrainList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(DnD.Terrain.TerrainListOuterClass.TerrainList other) {
        if (other == DnD.Terrain.TerrainListOuterClass.TerrainList.getDefaultInstance()) return this;
        if (terrainsBuilder_ == null) {
          if (!other.terrains_.isEmpty()) {
            if (terrains_.isEmpty()) {
              terrains_ = other.terrains_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureTerrainsIsMutable();
              terrains_.addAll(other.terrains_);
            }
            onChanged();
          }
        } else {
          if (!other.terrains_.isEmpty()) {
            if (terrainsBuilder_.isEmpty()) {
              terrainsBuilder_.dispose();
              terrainsBuilder_ = null;
              terrains_ = other.terrains_;
              bitField0_ = (bitField0_ & ~0x00000001);
              terrainsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getTerrainsFieldBuilder() : null;
            } else {
              terrainsBuilder_.addAllMessages(other.terrains_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        DnD.Terrain.TerrainListOuterClass.TerrainList parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (DnD.Terrain.TerrainListOuterClass.TerrainList) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<DnD.Terrain.TerrainOuterClass.Terrain> terrains_ =
        java.util.Collections.emptyList();
      private void ensureTerrainsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          terrains_ = new java.util.ArrayList<DnD.Terrain.TerrainOuterClass.Terrain>(terrains_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          DnD.Terrain.TerrainOuterClass.Terrain, DnD.Terrain.TerrainOuterClass.Terrain.Builder, DnD.Terrain.TerrainOuterClass.TerrainOrBuilder> terrainsBuilder_;

      /**
       * <code>repeated .Dnd.Terrain.Terrain terrains = 1;</code>
       */
      public java.util.List<DnD.Terrain.TerrainOuterClass.Terrain> getTerrainsList() {
        if (terrainsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(terrains_);
        } else {
          return terrainsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Dnd.Terrain.Terrain terrains = 1;</code>
       */
      public int getTerrainsCount() {
        if (terrainsBuilder_ == null) {
          return terrains_.size();
        } else {
          return terrainsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Dnd.Terrain.Terrain terrains = 1;</code>
       */
      public DnD.Terrain.TerrainOuterClass.Terrain getTerrains(int index) {
        if (terrainsBuilder_ == null) {
          return terrains_.get(index);
        } else {
          return terrainsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Dnd.Terrain.Terrain terrains = 1;</code>
       */
      public Builder setTerrains(
          int index, DnD.Terrain.TerrainOuterClass.Terrain value) {
        if (terrainsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTerrainsIsMutable();
          terrains_.set(index, value);
          onChanged();
        } else {
          terrainsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Dnd.Terrain.Terrain terrains = 1;</code>
       */
      public Builder setTerrains(
          int index, DnD.Terrain.TerrainOuterClass.Terrain.Builder builderForValue) {
        if (terrainsBuilder_ == null) {
          ensureTerrainsIsMutable();
          terrains_.set(index, builderForValue.build());
          onChanged();
        } else {
          terrainsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Dnd.Terrain.Terrain terrains = 1;</code>
       */
      public Builder addTerrains(DnD.Terrain.TerrainOuterClass.Terrain value) {
        if (terrainsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTerrainsIsMutable();
          terrains_.add(value);
          onChanged();
        } else {
          terrainsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Dnd.Terrain.Terrain terrains = 1;</code>
       */
      public Builder addTerrains(
          int index, DnD.Terrain.TerrainOuterClass.Terrain value) {
        if (terrainsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTerrainsIsMutable();
          terrains_.add(index, value);
          onChanged();
        } else {
          terrainsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Dnd.Terrain.Terrain terrains = 1;</code>
       */
      public Builder addTerrains(
          DnD.Terrain.TerrainOuterClass.Terrain.Builder builderForValue) {
        if (terrainsBuilder_ == null) {
          ensureTerrainsIsMutable();
          terrains_.add(builderForValue.build());
          onChanged();
        } else {
          terrainsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Dnd.Terrain.Terrain terrains = 1;</code>
       */
      public Builder addTerrains(
          int index, DnD.Terrain.TerrainOuterClass.Terrain.Builder builderForValue) {
        if (terrainsBuilder_ == null) {
          ensureTerrainsIsMutable();
          terrains_.add(index, builderForValue.build());
          onChanged();
        } else {
          terrainsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Dnd.Terrain.Terrain terrains = 1;</code>
       */
      public Builder addAllTerrains(
          java.lang.Iterable<? extends DnD.Terrain.TerrainOuterClass.Terrain> values) {
        if (terrainsBuilder_ == null) {
          ensureTerrainsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, terrains_);
          onChanged();
        } else {
          terrainsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Dnd.Terrain.Terrain terrains = 1;</code>
       */
      public Builder clearTerrains() {
        if (terrainsBuilder_ == null) {
          terrains_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          terrainsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Dnd.Terrain.Terrain terrains = 1;</code>
       */
      public Builder removeTerrains(int index) {
        if (terrainsBuilder_ == null) {
          ensureTerrainsIsMutable();
          terrains_.remove(index);
          onChanged();
        } else {
          terrainsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Dnd.Terrain.Terrain terrains = 1;</code>
       */
      public DnD.Terrain.TerrainOuterClass.Terrain.Builder getTerrainsBuilder(
          int index) {
        return getTerrainsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Dnd.Terrain.Terrain terrains = 1;</code>
       */
      public DnD.Terrain.TerrainOuterClass.TerrainOrBuilder getTerrainsOrBuilder(
          int index) {
        if (terrainsBuilder_ == null) {
          return terrains_.get(index);  } else {
          return terrainsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Dnd.Terrain.Terrain terrains = 1;</code>
       */
      public java.util.List<? extends DnD.Terrain.TerrainOuterClass.TerrainOrBuilder> 
           getTerrainsOrBuilderList() {
        if (terrainsBuilder_ != null) {
          return terrainsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(terrains_);
        }
      }
      /**
       * <code>repeated .Dnd.Terrain.Terrain terrains = 1;</code>
       */
      public DnD.Terrain.TerrainOuterClass.Terrain.Builder addTerrainsBuilder() {
        return getTerrainsFieldBuilder().addBuilder(
            DnD.Terrain.TerrainOuterClass.Terrain.getDefaultInstance());
      }
      /**
       * <code>repeated .Dnd.Terrain.Terrain terrains = 1;</code>
       */
      public DnD.Terrain.TerrainOuterClass.Terrain.Builder addTerrainsBuilder(
          int index) {
        return getTerrainsFieldBuilder().addBuilder(
            index, DnD.Terrain.TerrainOuterClass.Terrain.getDefaultInstance());
      }
      /**
       * <code>repeated .Dnd.Terrain.Terrain terrains = 1;</code>
       */
      public java.util.List<DnD.Terrain.TerrainOuterClass.Terrain.Builder> 
           getTerrainsBuilderList() {
        return getTerrainsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          DnD.Terrain.TerrainOuterClass.Terrain, DnD.Terrain.TerrainOuterClass.Terrain.Builder, DnD.Terrain.TerrainOuterClass.TerrainOrBuilder> 
          getTerrainsFieldBuilder() {
        if (terrainsBuilder_ == null) {
          terrainsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              DnD.Terrain.TerrainOuterClass.Terrain, DnD.Terrain.TerrainOuterClass.Terrain.Builder, DnD.Terrain.TerrainOuterClass.TerrainOrBuilder>(
                  terrains_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          terrains_ = null;
        }
        return terrainsBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:DnD.Terrain.TerrainList)
    }

    // @@protoc_insertion_point(class_scope:DnD.Terrain.TerrainList)
    private static final DnD.Terrain.TerrainListOuterClass.TerrainList DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new DnD.Terrain.TerrainListOuterClass.TerrainList();
    }

    public static DnD.Terrain.TerrainListOuterClass.TerrainList getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TerrainList>
        PARSER = new com.google.protobuf.AbstractParser<TerrainList>() {
      @java.lang.Override
      public TerrainList parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TerrainList(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TerrainList> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TerrainList> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public DnD.Terrain.TerrainListOuterClass.TerrainList getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DnD_Terrain_TerrainList_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DnD_Terrain_TerrainList_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021TerrainList.proto\022\013DnD.Terrain\032\rTerrai" +
      "n.proto\"5\n\013TerrainList\022&\n\010terrains\030\001 \003(\013" +
      "2\024.Dnd.Terrain.TerrainB$\n\013DnD.TerrainB\025T" +
      "errainListOuterClassb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          DnD.Terrain.TerrainOuterClass.getDescriptor(),
        });
    internal_static_DnD_Terrain_TerrainList_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_DnD_Terrain_TerrainList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DnD_Terrain_TerrainList_descriptor,
        new java.lang.String[] { "Terrains", });
    DnD.Terrain.TerrainOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
