// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Tile.proto

package DnD.Terrain;

public final class TileOuterClass {
  private TileOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TileOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Dnd.Terrain.Tile)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>float posX = 1;</code>
     * @return The posX.
     */
    float getPosX();

    /**
     * <code>float posY = 2;</code>
     * @return The posY.
     */
    float getPosY();

    /**
     * <code>.Dnd.Terrain.TileType type = 3;</code>
     * @return The enum numeric value on the wire for type.
     */
    int getTypeValue();
    /**
     * <code>.Dnd.Terrain.TileType type = 3;</code>
     * @return The type.
     */
    DnD.Terrain.TileTypeOuterClass.TileType getType();

    /**
     * <code>int32 variant = 4;</code>
     * @return The variant.
     */
    int getVariant();

    /**
     * <pre>
     * Decides where to spawn.
     * </pre>
     *
     * <code>repeated int32 spawnPositionIndicies = 5;</code>
     * @return A list containing the spawnPositionIndicies.
     */
    java.util.List<java.lang.Integer> getSpawnPositionIndiciesList();
    /**
     * <pre>
     * Decides where to spawn.
     * </pre>
     *
     * <code>repeated int32 spawnPositionIndicies = 5;</code>
     * @return The count of spawnPositionIndicies.
     */
    int getSpawnPositionIndiciesCount();
    /**
     * <pre>
     * Decides where to spawn.
     * </pre>
     *
     * <code>repeated int32 spawnPositionIndicies = 5;</code>
     * @param index The index of the element to return.
     * @return The spawnPositionIndicies at the given index.
     */
    int getSpawnPositionIndicies(int index);

    /**
     * <pre>
     * Decides what to spawn.
     * </pre>
     *
     * <code>repeated int32 spawnPositionObjects = 6;</code>
     * @return A list containing the spawnPositionObjects.
     */
    java.util.List<java.lang.Integer> getSpawnPositionObjectsList();
    /**
     * <pre>
     * Decides what to spawn.
     * </pre>
     *
     * <code>repeated int32 spawnPositionObjects = 6;</code>
     * @return The count of spawnPositionObjects.
     */
    int getSpawnPositionObjectsCount();
    /**
     * <pre>
     * Decides what to spawn.
     * </pre>
     *
     * <code>repeated int32 spawnPositionObjects = 6;</code>
     * @param index The index of the element to return.
     * @return The spawnPositionObjects at the given index.
     */
    int getSpawnPositionObjects(int index);

    /**
     * <code>float tileOffSetX = 7;</code>
     * @return The tileOffSetX.
     */
    float getTileOffSetX();

    /**
     * <code>float tileOffSetY = 8;</code>
     * @return The tileOffSetY.
     */
    float getTileOffSetY();
  }
  /**
   * Protobuf type {@code Dnd.Terrain.Tile}
   */
  public  static final class Tile extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Dnd.Terrain.Tile)
      TileOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Tile.newBuilder() to construct.
    private Tile(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Tile() {
      type_ = 0;
      spawnPositionIndicies_ = emptyIntList();
      spawnPositionObjects_ = emptyIntList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Tile();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Tile(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 13: {

              posX_ = input.readFloat();
              break;
            }
            case 21: {

              posY_ = input.readFloat();
              break;
            }
            case 24: {
              int rawValue = input.readEnum();

              type_ = rawValue;
              break;
            }
            case 32: {

              variant_ = input.readInt32();
              break;
            }
            case 40: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                spawnPositionIndicies_ = newIntList();
                mutable_bitField0_ |= 0x00000001;
              }
              spawnPositionIndicies_.addInt(input.readInt32());
              break;
            }
            case 42: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000001) != 0) && input.getBytesUntilLimit() > 0) {
                spawnPositionIndicies_ = newIntList();
                mutable_bitField0_ |= 0x00000001;
              }
              while (input.getBytesUntilLimit() > 0) {
                spawnPositionIndicies_.addInt(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
            case 48: {
              if (!((mutable_bitField0_ & 0x00000002) != 0)) {
                spawnPositionObjects_ = newIntList();
                mutable_bitField0_ |= 0x00000002;
              }
              spawnPositionObjects_.addInt(input.readInt32());
              break;
            }
            case 50: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000002) != 0) && input.getBytesUntilLimit() > 0) {
                spawnPositionObjects_ = newIntList();
                mutable_bitField0_ |= 0x00000002;
              }
              while (input.getBytesUntilLimit() > 0) {
                spawnPositionObjects_.addInt(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
            case 61: {

              tileOffSetX_ = input.readFloat();
              break;
            }
            case 69: {

              tileOffSetY_ = input.readFloat();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          spawnPositionIndicies_.makeImmutable(); // C
        }
        if (((mutable_bitField0_ & 0x00000002) != 0)) {
          spawnPositionObjects_.makeImmutable(); // C
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return DnD.Terrain.TileOuterClass.internal_static_Dnd_Terrain_Tile_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return DnD.Terrain.TileOuterClass.internal_static_Dnd_Terrain_Tile_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              DnD.Terrain.TileOuterClass.Tile.class, DnD.Terrain.TileOuterClass.Tile.Builder.class);
    }

    public static final int POSX_FIELD_NUMBER = 1;
    private float posX_;
    /**
     * <code>float posX = 1;</code>
     * @return The posX.
     */
    public float getPosX() {
      return posX_;
    }

    public static final int POSY_FIELD_NUMBER = 2;
    private float posY_;
    /**
     * <code>float posY = 2;</code>
     * @return The posY.
     */
    public float getPosY() {
      return posY_;
    }

    public static final int TYPE_FIELD_NUMBER = 3;
    private int type_;
    /**
     * <code>.Dnd.Terrain.TileType type = 3;</code>
     * @return The enum numeric value on the wire for type.
     */
    public int getTypeValue() {
      return type_;
    }
    /**
     * <code>.Dnd.Terrain.TileType type = 3;</code>
     * @return The type.
     */
    public DnD.Terrain.TileTypeOuterClass.TileType getType() {
      @SuppressWarnings("deprecation")
      DnD.Terrain.TileTypeOuterClass.TileType result = DnD.Terrain.TileTypeOuterClass.TileType.valueOf(type_);
      return result == null ? DnD.Terrain.TileTypeOuterClass.TileType.UNRECOGNIZED : result;
    }

    public static final int VARIANT_FIELD_NUMBER = 4;
    private int variant_;
    /**
     * <code>int32 variant = 4;</code>
     * @return The variant.
     */
    public int getVariant() {
      return variant_;
    }

    public static final int SPAWNPOSITIONINDICIES_FIELD_NUMBER = 5;
    private com.google.protobuf.Internal.IntList spawnPositionIndicies_;
    /**
     * <pre>
     * Decides where to spawn.
     * </pre>
     *
     * <code>repeated int32 spawnPositionIndicies = 5;</code>
     * @return A list containing the spawnPositionIndicies.
     */
    public java.util.List<java.lang.Integer>
        getSpawnPositionIndiciesList() {
      return spawnPositionIndicies_;
    }
    /**
     * <pre>
     * Decides where to spawn.
     * </pre>
     *
     * <code>repeated int32 spawnPositionIndicies = 5;</code>
     * @return The count of spawnPositionIndicies.
     */
    public int getSpawnPositionIndiciesCount() {
      return spawnPositionIndicies_.size();
    }
    /**
     * <pre>
     * Decides where to spawn.
     * </pre>
     *
     * <code>repeated int32 spawnPositionIndicies = 5;</code>
     * @param index The index of the element to return.
     * @return The spawnPositionIndicies at the given index.
     */
    public int getSpawnPositionIndicies(int index) {
      return spawnPositionIndicies_.getInt(index);
    }
    private int spawnPositionIndiciesMemoizedSerializedSize = -1;

    public static final int SPAWNPOSITIONOBJECTS_FIELD_NUMBER = 6;
    private com.google.protobuf.Internal.IntList spawnPositionObjects_;
    /**
     * <pre>
     * Decides what to spawn.
     * </pre>
     *
     * <code>repeated int32 spawnPositionObjects = 6;</code>
     * @return A list containing the spawnPositionObjects.
     */
    public java.util.List<java.lang.Integer>
        getSpawnPositionObjectsList() {
      return spawnPositionObjects_;
    }
    /**
     * <pre>
     * Decides what to spawn.
     * </pre>
     *
     * <code>repeated int32 spawnPositionObjects = 6;</code>
     * @return The count of spawnPositionObjects.
     */
    public int getSpawnPositionObjectsCount() {
      return spawnPositionObjects_.size();
    }
    /**
     * <pre>
     * Decides what to spawn.
     * </pre>
     *
     * <code>repeated int32 spawnPositionObjects = 6;</code>
     * @param index The index of the element to return.
     * @return The spawnPositionObjects at the given index.
     */
    public int getSpawnPositionObjects(int index) {
      return spawnPositionObjects_.getInt(index);
    }
    private int spawnPositionObjectsMemoizedSerializedSize = -1;

    public static final int TILEOFFSETX_FIELD_NUMBER = 7;
    private float tileOffSetX_;
    /**
     * <code>float tileOffSetX = 7;</code>
     * @return The tileOffSetX.
     */
    public float getTileOffSetX() {
      return tileOffSetX_;
    }

    public static final int TILEOFFSETY_FIELD_NUMBER = 8;
    private float tileOffSetY_;
    /**
     * <code>float tileOffSetY = 8;</code>
     * @return The tileOffSetY.
     */
    public float getTileOffSetY() {
      return tileOffSetY_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (posX_ != 0F) {
        output.writeFloat(1, posX_);
      }
      if (posY_ != 0F) {
        output.writeFloat(2, posY_);
      }
      if (type_ != DnD.Terrain.TileTypeOuterClass.TileType.STANDARD_GRASS.getNumber()) {
        output.writeEnum(3, type_);
      }
      if (variant_ != 0) {
        output.writeInt32(4, variant_);
      }
      if (getSpawnPositionIndiciesList().size() > 0) {
        output.writeUInt32NoTag(42);
        output.writeUInt32NoTag(spawnPositionIndiciesMemoizedSerializedSize);
      }
      for (int i = 0; i < spawnPositionIndicies_.size(); i++) {
        output.writeInt32NoTag(spawnPositionIndicies_.getInt(i));
      }
      if (getSpawnPositionObjectsList().size() > 0) {
        output.writeUInt32NoTag(50);
        output.writeUInt32NoTag(spawnPositionObjectsMemoizedSerializedSize);
      }
      for (int i = 0; i < spawnPositionObjects_.size(); i++) {
        output.writeInt32NoTag(spawnPositionObjects_.getInt(i));
      }
      if (tileOffSetX_ != 0F) {
        output.writeFloat(7, tileOffSetX_);
      }
      if (tileOffSetY_ != 0F) {
        output.writeFloat(8, tileOffSetY_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (posX_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(1, posX_);
      }
      if (posY_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(2, posY_);
      }
      if (type_ != DnD.Terrain.TileTypeOuterClass.TileType.STANDARD_GRASS.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, type_);
      }
      if (variant_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, variant_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < spawnPositionIndicies_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(spawnPositionIndicies_.getInt(i));
        }
        size += dataSize;
        if (!getSpawnPositionIndiciesList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        spawnPositionIndiciesMemoizedSerializedSize = dataSize;
      }
      {
        int dataSize = 0;
        for (int i = 0; i < spawnPositionObjects_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(spawnPositionObjects_.getInt(i));
        }
        size += dataSize;
        if (!getSpawnPositionObjectsList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        spawnPositionObjectsMemoizedSerializedSize = dataSize;
      }
      if (tileOffSetX_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(7, tileOffSetX_);
      }
      if (tileOffSetY_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(8, tileOffSetY_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof DnD.Terrain.TileOuterClass.Tile)) {
        return super.equals(obj);
      }
      DnD.Terrain.TileOuterClass.Tile other = (DnD.Terrain.TileOuterClass.Tile) obj;

      if (java.lang.Float.floatToIntBits(getPosX())
          != java.lang.Float.floatToIntBits(
              other.getPosX())) return false;
      if (java.lang.Float.floatToIntBits(getPosY())
          != java.lang.Float.floatToIntBits(
              other.getPosY())) return false;
      if (type_ != other.type_) return false;
      if (getVariant()
          != other.getVariant()) return false;
      if (!getSpawnPositionIndiciesList()
          .equals(other.getSpawnPositionIndiciesList())) return false;
      if (!getSpawnPositionObjectsList()
          .equals(other.getSpawnPositionObjectsList())) return false;
      if (java.lang.Float.floatToIntBits(getTileOffSetX())
          != java.lang.Float.floatToIntBits(
              other.getTileOffSetX())) return false;
      if (java.lang.Float.floatToIntBits(getTileOffSetY())
          != java.lang.Float.floatToIntBits(
              other.getTileOffSetY())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + POSX_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getPosX());
      hash = (37 * hash) + POSY_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getPosY());
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
      hash = (37 * hash) + VARIANT_FIELD_NUMBER;
      hash = (53 * hash) + getVariant();
      if (getSpawnPositionIndiciesCount() > 0) {
        hash = (37 * hash) + SPAWNPOSITIONINDICIES_FIELD_NUMBER;
        hash = (53 * hash) + getSpawnPositionIndiciesList().hashCode();
      }
      if (getSpawnPositionObjectsCount() > 0) {
        hash = (37 * hash) + SPAWNPOSITIONOBJECTS_FIELD_NUMBER;
        hash = (53 * hash) + getSpawnPositionObjectsList().hashCode();
      }
      hash = (37 * hash) + TILEOFFSETX_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getTileOffSetX());
      hash = (37 * hash) + TILEOFFSETY_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getTileOffSetY());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static DnD.Terrain.TileOuterClass.Tile parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static DnD.Terrain.TileOuterClass.Tile parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static DnD.Terrain.TileOuterClass.Tile parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static DnD.Terrain.TileOuterClass.Tile parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static DnD.Terrain.TileOuterClass.Tile parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static DnD.Terrain.TileOuterClass.Tile parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static DnD.Terrain.TileOuterClass.Tile parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static DnD.Terrain.TileOuterClass.Tile parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static DnD.Terrain.TileOuterClass.Tile parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static DnD.Terrain.TileOuterClass.Tile parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static DnD.Terrain.TileOuterClass.Tile parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static DnD.Terrain.TileOuterClass.Tile parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(DnD.Terrain.TileOuterClass.Tile prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Dnd.Terrain.Tile}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Dnd.Terrain.Tile)
        DnD.Terrain.TileOuterClass.TileOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return DnD.Terrain.TileOuterClass.internal_static_Dnd_Terrain_Tile_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return DnD.Terrain.TileOuterClass.internal_static_Dnd_Terrain_Tile_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                DnD.Terrain.TileOuterClass.Tile.class, DnD.Terrain.TileOuterClass.Tile.Builder.class);
      }

      // Construct using DnD.Terrain.TileOuterClass.Tile.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        posX_ = 0F;

        posY_ = 0F;

        type_ = 0;

        variant_ = 0;

        spawnPositionIndicies_ = emptyIntList();
        bitField0_ = (bitField0_ & ~0x00000001);
        spawnPositionObjects_ = emptyIntList();
        bitField0_ = (bitField0_ & ~0x00000002);
        tileOffSetX_ = 0F;

        tileOffSetY_ = 0F;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return DnD.Terrain.TileOuterClass.internal_static_Dnd_Terrain_Tile_descriptor;
      }

      @java.lang.Override
      public DnD.Terrain.TileOuterClass.Tile getDefaultInstanceForType() {
        return DnD.Terrain.TileOuterClass.Tile.getDefaultInstance();
      }

      @java.lang.Override
      public DnD.Terrain.TileOuterClass.Tile build() {
        DnD.Terrain.TileOuterClass.Tile result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public DnD.Terrain.TileOuterClass.Tile buildPartial() {
        DnD.Terrain.TileOuterClass.Tile result = new DnD.Terrain.TileOuterClass.Tile(this);
        int from_bitField0_ = bitField0_;
        result.posX_ = posX_;
        result.posY_ = posY_;
        result.type_ = type_;
        result.variant_ = variant_;
        if (((bitField0_ & 0x00000001) != 0)) {
          spawnPositionIndicies_.makeImmutable();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.spawnPositionIndicies_ = spawnPositionIndicies_;
        if (((bitField0_ & 0x00000002) != 0)) {
          spawnPositionObjects_.makeImmutable();
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.spawnPositionObjects_ = spawnPositionObjects_;
        result.tileOffSetX_ = tileOffSetX_;
        result.tileOffSetY_ = tileOffSetY_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof DnD.Terrain.TileOuterClass.Tile) {
          return mergeFrom((DnD.Terrain.TileOuterClass.Tile)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(DnD.Terrain.TileOuterClass.Tile other) {
        if (other == DnD.Terrain.TileOuterClass.Tile.getDefaultInstance()) return this;
        if (other.getPosX() != 0F) {
          setPosX(other.getPosX());
        }
        if (other.getPosY() != 0F) {
          setPosY(other.getPosY());
        }
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        if (other.getVariant() != 0) {
          setVariant(other.getVariant());
        }
        if (!other.spawnPositionIndicies_.isEmpty()) {
          if (spawnPositionIndicies_.isEmpty()) {
            spawnPositionIndicies_ = other.spawnPositionIndicies_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureSpawnPositionIndiciesIsMutable();
            spawnPositionIndicies_.addAll(other.spawnPositionIndicies_);
          }
          onChanged();
        }
        if (!other.spawnPositionObjects_.isEmpty()) {
          if (spawnPositionObjects_.isEmpty()) {
            spawnPositionObjects_ = other.spawnPositionObjects_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureSpawnPositionObjectsIsMutable();
            spawnPositionObjects_.addAll(other.spawnPositionObjects_);
          }
          onChanged();
        }
        if (other.getTileOffSetX() != 0F) {
          setTileOffSetX(other.getTileOffSetX());
        }
        if (other.getTileOffSetY() != 0F) {
          setTileOffSetY(other.getTileOffSetY());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        DnD.Terrain.TileOuterClass.Tile parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (DnD.Terrain.TileOuterClass.Tile) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private float posX_ ;
      /**
       * <code>float posX = 1;</code>
       * @return The posX.
       */
      public float getPosX() {
        return posX_;
      }
      /**
       * <code>float posX = 1;</code>
       * @param value The posX to set.
       * @return This builder for chaining.
       */
      public Builder setPosX(float value) {
        
        posX_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float posX = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearPosX() {
        
        posX_ = 0F;
        onChanged();
        return this;
      }

      private float posY_ ;
      /**
       * <code>float posY = 2;</code>
       * @return The posY.
       */
      public float getPosY() {
        return posY_;
      }
      /**
       * <code>float posY = 2;</code>
       * @param value The posY to set.
       * @return This builder for chaining.
       */
      public Builder setPosY(float value) {
        
        posY_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float posY = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearPosY() {
        
        posY_ = 0F;
        onChanged();
        return this;
      }

      private int type_ = 0;
      /**
       * <code>.Dnd.Terrain.TileType type = 3;</code>
       * @return The enum numeric value on the wire for type.
       */
      public int getTypeValue() {
        return type_;
      }
      /**
       * <code>.Dnd.Terrain.TileType type = 3;</code>
       * @param value The enum numeric value on the wire for type to set.
       * @return This builder for chaining.
       */
      public Builder setTypeValue(int value) {
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.Dnd.Terrain.TileType type = 3;</code>
       * @return The type.
       */
      public DnD.Terrain.TileTypeOuterClass.TileType getType() {
        @SuppressWarnings("deprecation")
        DnD.Terrain.TileTypeOuterClass.TileType result = DnD.Terrain.TileTypeOuterClass.TileType.valueOf(type_);
        return result == null ? DnD.Terrain.TileTypeOuterClass.TileType.UNRECOGNIZED : result;
      }
      /**
       * <code>.Dnd.Terrain.TileType type = 3;</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(DnD.Terrain.TileTypeOuterClass.TileType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.Dnd.Terrain.TileType type = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }

      private int variant_ ;
      /**
       * <code>int32 variant = 4;</code>
       * @return The variant.
       */
      public int getVariant() {
        return variant_;
      }
      /**
       * <code>int32 variant = 4;</code>
       * @param value The variant to set.
       * @return This builder for chaining.
       */
      public Builder setVariant(int value) {
        
        variant_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 variant = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearVariant() {
        
        variant_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.Internal.IntList spawnPositionIndicies_ = emptyIntList();
      private void ensureSpawnPositionIndiciesIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          spawnPositionIndicies_ = mutableCopy(spawnPositionIndicies_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <pre>
       * Decides where to spawn.
       * </pre>
       *
       * <code>repeated int32 spawnPositionIndicies = 5;</code>
       * @return A list containing the spawnPositionIndicies.
       */
      public java.util.List<java.lang.Integer>
          getSpawnPositionIndiciesList() {
        return ((bitField0_ & 0x00000001) != 0) ?
                 java.util.Collections.unmodifiableList(spawnPositionIndicies_) : spawnPositionIndicies_;
      }
      /**
       * <pre>
       * Decides where to spawn.
       * </pre>
       *
       * <code>repeated int32 spawnPositionIndicies = 5;</code>
       * @return The count of spawnPositionIndicies.
       */
      public int getSpawnPositionIndiciesCount() {
        return spawnPositionIndicies_.size();
      }
      /**
       * <pre>
       * Decides where to spawn.
       * </pre>
       *
       * <code>repeated int32 spawnPositionIndicies = 5;</code>
       * @param index The index of the element to return.
       * @return The spawnPositionIndicies at the given index.
       */
      public int getSpawnPositionIndicies(int index) {
        return spawnPositionIndicies_.getInt(index);
      }
      /**
       * <pre>
       * Decides where to spawn.
       * </pre>
       *
       * <code>repeated int32 spawnPositionIndicies = 5;</code>
       * @param index The index to set the value at.
       * @param value The spawnPositionIndicies to set.
       * @return This builder for chaining.
       */
      public Builder setSpawnPositionIndicies(
          int index, int value) {
        ensureSpawnPositionIndiciesIsMutable();
        spawnPositionIndicies_.setInt(index, value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Decides where to spawn.
       * </pre>
       *
       * <code>repeated int32 spawnPositionIndicies = 5;</code>
       * @param value The spawnPositionIndicies to add.
       * @return This builder for chaining.
       */
      public Builder addSpawnPositionIndicies(int value) {
        ensureSpawnPositionIndiciesIsMutable();
        spawnPositionIndicies_.addInt(value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Decides where to spawn.
       * </pre>
       *
       * <code>repeated int32 spawnPositionIndicies = 5;</code>
       * @param values The spawnPositionIndicies to add.
       * @return This builder for chaining.
       */
      public Builder addAllSpawnPositionIndicies(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureSpawnPositionIndiciesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, spawnPositionIndicies_);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Decides where to spawn.
       * </pre>
       *
       * <code>repeated int32 spawnPositionIndicies = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearSpawnPositionIndicies() {
        spawnPositionIndicies_ = emptyIntList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }

      private com.google.protobuf.Internal.IntList spawnPositionObjects_ = emptyIntList();
      private void ensureSpawnPositionObjectsIsMutable() {
        if (!((bitField0_ & 0x00000002) != 0)) {
          spawnPositionObjects_ = mutableCopy(spawnPositionObjects_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <pre>
       * Decides what to spawn.
       * </pre>
       *
       * <code>repeated int32 spawnPositionObjects = 6;</code>
       * @return A list containing the spawnPositionObjects.
       */
      public java.util.List<java.lang.Integer>
          getSpawnPositionObjectsList() {
        return ((bitField0_ & 0x00000002) != 0) ?
                 java.util.Collections.unmodifiableList(spawnPositionObjects_) : spawnPositionObjects_;
      }
      /**
       * <pre>
       * Decides what to spawn.
       * </pre>
       *
       * <code>repeated int32 spawnPositionObjects = 6;</code>
       * @return The count of spawnPositionObjects.
       */
      public int getSpawnPositionObjectsCount() {
        return spawnPositionObjects_.size();
      }
      /**
       * <pre>
       * Decides what to spawn.
       * </pre>
       *
       * <code>repeated int32 spawnPositionObjects = 6;</code>
       * @param index The index of the element to return.
       * @return The spawnPositionObjects at the given index.
       */
      public int getSpawnPositionObjects(int index) {
        return spawnPositionObjects_.getInt(index);
      }
      /**
       * <pre>
       * Decides what to spawn.
       * </pre>
       *
       * <code>repeated int32 spawnPositionObjects = 6;</code>
       * @param index The index to set the value at.
       * @param value The spawnPositionObjects to set.
       * @return This builder for chaining.
       */
      public Builder setSpawnPositionObjects(
          int index, int value) {
        ensureSpawnPositionObjectsIsMutable();
        spawnPositionObjects_.setInt(index, value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Decides what to spawn.
       * </pre>
       *
       * <code>repeated int32 spawnPositionObjects = 6;</code>
       * @param value The spawnPositionObjects to add.
       * @return This builder for chaining.
       */
      public Builder addSpawnPositionObjects(int value) {
        ensureSpawnPositionObjectsIsMutable();
        spawnPositionObjects_.addInt(value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Decides what to spawn.
       * </pre>
       *
       * <code>repeated int32 spawnPositionObjects = 6;</code>
       * @param values The spawnPositionObjects to add.
       * @return This builder for chaining.
       */
      public Builder addAllSpawnPositionObjects(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureSpawnPositionObjectsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, spawnPositionObjects_);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Decides what to spawn.
       * </pre>
       *
       * <code>repeated int32 spawnPositionObjects = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearSpawnPositionObjects() {
        spawnPositionObjects_ = emptyIntList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }

      private float tileOffSetX_ ;
      /**
       * <code>float tileOffSetX = 7;</code>
       * @return The tileOffSetX.
       */
      public float getTileOffSetX() {
        return tileOffSetX_;
      }
      /**
       * <code>float tileOffSetX = 7;</code>
       * @param value The tileOffSetX to set.
       * @return This builder for chaining.
       */
      public Builder setTileOffSetX(float value) {
        
        tileOffSetX_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float tileOffSetX = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearTileOffSetX() {
        
        tileOffSetX_ = 0F;
        onChanged();
        return this;
      }

      private float tileOffSetY_ ;
      /**
       * <code>float tileOffSetY = 8;</code>
       * @return The tileOffSetY.
       */
      public float getTileOffSetY() {
        return tileOffSetY_;
      }
      /**
       * <code>float tileOffSetY = 8;</code>
       * @param value The tileOffSetY to set.
       * @return This builder for chaining.
       */
      public Builder setTileOffSetY(float value) {
        
        tileOffSetY_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float tileOffSetY = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearTileOffSetY() {
        
        tileOffSetY_ = 0F;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Dnd.Terrain.Tile)
    }

    // @@protoc_insertion_point(class_scope:Dnd.Terrain.Tile)
    private static final DnD.Terrain.TileOuterClass.Tile DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new DnD.Terrain.TileOuterClass.Tile();
    }

    public static DnD.Terrain.TileOuterClass.Tile getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Tile>
        PARSER = new com.google.protobuf.AbstractParser<Tile>() {
      @java.lang.Override
      public Tile parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Tile(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Tile> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Tile> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public DnD.Terrain.TileOuterClass.Tile getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Dnd_Terrain_Tile_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Dnd_Terrain_Tile_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nTile.proto\022\013Dnd.Terrain\032\016TileType.prot" +
      "o\"\277\001\n\004Tile\022\014\n\004posX\030\001 \001(\002\022\014\n\004posY\030\002 \001(\002\022#" +
      "\n\004type\030\003 \001(\0162\025.Dnd.Terrain.TileType\022\017\n\007v" +
      "ariant\030\004 \001(\005\022\035\n\025spawnPositionIndicies\030\005 " +
      "\003(\005\022\034\n\024spawnPositionObjects\030\006 \003(\005\022\023\n\013til" +
      "eOffSetX\030\007 \001(\002\022\023\n\013tileOffSetY\030\010 \001(\002B\035\n\013D" +
      "nD.TerrainB\016TileOuterClassb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          DnD.Terrain.TileTypeOuterClass.getDescriptor(),
        });
    internal_static_Dnd_Terrain_Tile_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Dnd_Terrain_Tile_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Dnd_Terrain_Tile_descriptor,
        new java.lang.String[] { "PosX", "PosY", "Type", "Variant", "SpawnPositionIndicies", "SpawnPositionObjects", "TileOffSetX", "TileOffSetY", });
    DnD.Terrain.TileTypeOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
