// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TileItemData.proto

package DnD.Terrain;

public final class TileItemDataOuterClass {
  private TileItemDataOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code DnD.Terrain.TileItemDataType}
   */
  public enum TileItemDataType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>DELETE = 0;</code>
     */
    DELETE(0),
    /**
     * <code>UPDATE = 1;</code>
     */
    UPDATE(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>DELETE = 0;</code>
     */
    public static final int DELETE_VALUE = 0;
    /**
     * <code>UPDATE = 1;</code>
     */
    public static final int UPDATE_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static TileItemDataType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static TileItemDataType forNumber(int value) {
      switch (value) {
        case 0: return DELETE;
        case 1: return UPDATE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<TileItemDataType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        TileItemDataType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<TileItemDataType>() {
            public TileItemDataType findValueByNumber(int number) {
              return TileItemDataType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return DnD.Terrain.TileItemDataOuterClass.getDescriptor().getEnumTypes().get(0);
    }

    private static final TileItemDataType[] VALUES = values();

    public static TileItemDataType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private TileItemDataType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:DnD.Terrain.TileItemDataType)
  }

  public interface TileItemDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:DnD.Terrain.TileItemData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>float posX = 1;</code>
     * @return The posX.
     */
    float getPosX();

    /**
     * <code>float posY = 2;</code>
     * @return The posY.
     */
    float getPosY();

    /**
     * <code>float terrainPosX = 3;</code>
     * @return The terrainPosX.
     */
    float getTerrainPosX();

    /**
     * <code>float terrainPosY = 4;</code>
     * @return The terrainPosY.
     */
    float getTerrainPosY();

    /**
     * <code>.DnD.Terrain.TileItemDataType type = 5;</code>
     * @return The enum numeric value on the wire for type.
     */
    int getTypeValue();
    /**
     * <code>.DnD.Terrain.TileItemDataType type = 5;</code>
     * @return The type.
     */
    DnD.Terrain.TileItemDataOuterClass.TileItemDataType getType();
  }
  /**
   * Protobuf type {@code DnD.Terrain.TileItemData}
   */
  public  static final class TileItemData extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:DnD.Terrain.TileItemData)
      TileItemDataOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TileItemData.newBuilder() to construct.
    private TileItemData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TileItemData() {
      type_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new TileItemData();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private TileItemData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 13: {

              posX_ = input.readFloat();
              break;
            }
            case 21: {

              posY_ = input.readFloat();
              break;
            }
            case 29: {

              terrainPosX_ = input.readFloat();
              break;
            }
            case 37: {

              terrainPosY_ = input.readFloat();
              break;
            }
            case 40: {
              int rawValue = input.readEnum();

              type_ = rawValue;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return DnD.Terrain.TileItemDataOuterClass.internal_static_DnD_Terrain_TileItemData_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return DnD.Terrain.TileItemDataOuterClass.internal_static_DnD_Terrain_TileItemData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              DnD.Terrain.TileItemDataOuterClass.TileItemData.class, DnD.Terrain.TileItemDataOuterClass.TileItemData.Builder.class);
    }

    public static final int POSX_FIELD_NUMBER = 1;
    private float posX_;
    /**
     * <code>float posX = 1;</code>
     * @return The posX.
     */
    public float getPosX() {
      return posX_;
    }

    public static final int POSY_FIELD_NUMBER = 2;
    private float posY_;
    /**
     * <code>float posY = 2;</code>
     * @return The posY.
     */
    public float getPosY() {
      return posY_;
    }

    public static final int TERRAINPOSX_FIELD_NUMBER = 3;
    private float terrainPosX_;
    /**
     * <code>float terrainPosX = 3;</code>
     * @return The terrainPosX.
     */
    public float getTerrainPosX() {
      return terrainPosX_;
    }

    public static final int TERRAINPOSY_FIELD_NUMBER = 4;
    private float terrainPosY_;
    /**
     * <code>float terrainPosY = 4;</code>
     * @return The terrainPosY.
     */
    public float getTerrainPosY() {
      return terrainPosY_;
    }

    public static final int TYPE_FIELD_NUMBER = 5;
    private int type_;
    /**
     * <code>.DnD.Terrain.TileItemDataType type = 5;</code>
     * @return The enum numeric value on the wire for type.
     */
    public int getTypeValue() {
      return type_;
    }
    /**
     * <code>.DnD.Terrain.TileItemDataType type = 5;</code>
     * @return The type.
     */
    public DnD.Terrain.TileItemDataOuterClass.TileItemDataType getType() {
      @SuppressWarnings("deprecation")
      DnD.Terrain.TileItemDataOuterClass.TileItemDataType result = DnD.Terrain.TileItemDataOuterClass.TileItemDataType.valueOf(type_);
      return result == null ? DnD.Terrain.TileItemDataOuterClass.TileItemDataType.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (posX_ != 0F) {
        output.writeFloat(1, posX_);
      }
      if (posY_ != 0F) {
        output.writeFloat(2, posY_);
      }
      if (terrainPosX_ != 0F) {
        output.writeFloat(3, terrainPosX_);
      }
      if (terrainPosY_ != 0F) {
        output.writeFloat(4, terrainPosY_);
      }
      if (type_ != DnD.Terrain.TileItemDataOuterClass.TileItemDataType.DELETE.getNumber()) {
        output.writeEnum(5, type_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (posX_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(1, posX_);
      }
      if (posY_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(2, posY_);
      }
      if (terrainPosX_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(3, terrainPosX_);
      }
      if (terrainPosY_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(4, terrainPosY_);
      }
      if (type_ != DnD.Terrain.TileItemDataOuterClass.TileItemDataType.DELETE.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(5, type_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof DnD.Terrain.TileItemDataOuterClass.TileItemData)) {
        return super.equals(obj);
      }
      DnD.Terrain.TileItemDataOuterClass.TileItemData other = (DnD.Terrain.TileItemDataOuterClass.TileItemData) obj;

      if (java.lang.Float.floatToIntBits(getPosX())
          != java.lang.Float.floatToIntBits(
              other.getPosX())) return false;
      if (java.lang.Float.floatToIntBits(getPosY())
          != java.lang.Float.floatToIntBits(
              other.getPosY())) return false;
      if (java.lang.Float.floatToIntBits(getTerrainPosX())
          != java.lang.Float.floatToIntBits(
              other.getTerrainPosX())) return false;
      if (java.lang.Float.floatToIntBits(getTerrainPosY())
          != java.lang.Float.floatToIntBits(
              other.getTerrainPosY())) return false;
      if (type_ != other.type_) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + POSX_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getPosX());
      hash = (37 * hash) + POSY_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getPosY());
      hash = (37 * hash) + TERRAINPOSX_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getTerrainPosX());
      hash = (37 * hash) + TERRAINPOSY_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getTerrainPosY());
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static DnD.Terrain.TileItemDataOuterClass.TileItemData parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static DnD.Terrain.TileItemDataOuterClass.TileItemData parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static DnD.Terrain.TileItemDataOuterClass.TileItemData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static DnD.Terrain.TileItemDataOuterClass.TileItemData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static DnD.Terrain.TileItemDataOuterClass.TileItemData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static DnD.Terrain.TileItemDataOuterClass.TileItemData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static DnD.Terrain.TileItemDataOuterClass.TileItemData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static DnD.Terrain.TileItemDataOuterClass.TileItemData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static DnD.Terrain.TileItemDataOuterClass.TileItemData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static DnD.Terrain.TileItemDataOuterClass.TileItemData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static DnD.Terrain.TileItemDataOuterClass.TileItemData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static DnD.Terrain.TileItemDataOuterClass.TileItemData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(DnD.Terrain.TileItemDataOuterClass.TileItemData prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code DnD.Terrain.TileItemData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:DnD.Terrain.TileItemData)
        DnD.Terrain.TileItemDataOuterClass.TileItemDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return DnD.Terrain.TileItemDataOuterClass.internal_static_DnD_Terrain_TileItemData_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return DnD.Terrain.TileItemDataOuterClass.internal_static_DnD_Terrain_TileItemData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                DnD.Terrain.TileItemDataOuterClass.TileItemData.class, DnD.Terrain.TileItemDataOuterClass.TileItemData.Builder.class);
      }

      // Construct using DnD.Terrain.TileItemDataOuterClass.TileItemData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        posX_ = 0F;

        posY_ = 0F;

        terrainPosX_ = 0F;

        terrainPosY_ = 0F;

        type_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return DnD.Terrain.TileItemDataOuterClass.internal_static_DnD_Terrain_TileItemData_descriptor;
      }

      @java.lang.Override
      public DnD.Terrain.TileItemDataOuterClass.TileItemData getDefaultInstanceForType() {
        return DnD.Terrain.TileItemDataOuterClass.TileItemData.getDefaultInstance();
      }

      @java.lang.Override
      public DnD.Terrain.TileItemDataOuterClass.TileItemData build() {
        DnD.Terrain.TileItemDataOuterClass.TileItemData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public DnD.Terrain.TileItemDataOuterClass.TileItemData buildPartial() {
        DnD.Terrain.TileItemDataOuterClass.TileItemData result = new DnD.Terrain.TileItemDataOuterClass.TileItemData(this);
        result.posX_ = posX_;
        result.posY_ = posY_;
        result.terrainPosX_ = terrainPosX_;
        result.terrainPosY_ = terrainPosY_;
        result.type_ = type_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof DnD.Terrain.TileItemDataOuterClass.TileItemData) {
          return mergeFrom((DnD.Terrain.TileItemDataOuterClass.TileItemData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(DnD.Terrain.TileItemDataOuterClass.TileItemData other) {
        if (other == DnD.Terrain.TileItemDataOuterClass.TileItemData.getDefaultInstance()) return this;
        if (other.getPosX() != 0F) {
          setPosX(other.getPosX());
        }
        if (other.getPosY() != 0F) {
          setPosY(other.getPosY());
        }
        if (other.getTerrainPosX() != 0F) {
          setTerrainPosX(other.getTerrainPosX());
        }
        if (other.getTerrainPosY() != 0F) {
          setTerrainPosY(other.getTerrainPosY());
        }
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        DnD.Terrain.TileItemDataOuterClass.TileItemData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (DnD.Terrain.TileItemDataOuterClass.TileItemData) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private float posX_ ;
      /**
       * <code>float posX = 1;</code>
       * @return The posX.
       */
      public float getPosX() {
        return posX_;
      }
      /**
       * <code>float posX = 1;</code>
       * @param value The posX to set.
       * @return This builder for chaining.
       */
      public Builder setPosX(float value) {
        
        posX_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float posX = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearPosX() {
        
        posX_ = 0F;
        onChanged();
        return this;
      }

      private float posY_ ;
      /**
       * <code>float posY = 2;</code>
       * @return The posY.
       */
      public float getPosY() {
        return posY_;
      }
      /**
       * <code>float posY = 2;</code>
       * @param value The posY to set.
       * @return This builder for chaining.
       */
      public Builder setPosY(float value) {
        
        posY_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float posY = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearPosY() {
        
        posY_ = 0F;
        onChanged();
        return this;
      }

      private float terrainPosX_ ;
      /**
       * <code>float terrainPosX = 3;</code>
       * @return The terrainPosX.
       */
      public float getTerrainPosX() {
        return terrainPosX_;
      }
      /**
       * <code>float terrainPosX = 3;</code>
       * @param value The terrainPosX to set.
       * @return This builder for chaining.
       */
      public Builder setTerrainPosX(float value) {
        
        terrainPosX_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float terrainPosX = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearTerrainPosX() {
        
        terrainPosX_ = 0F;
        onChanged();
        return this;
      }

      private float terrainPosY_ ;
      /**
       * <code>float terrainPosY = 4;</code>
       * @return The terrainPosY.
       */
      public float getTerrainPosY() {
        return terrainPosY_;
      }
      /**
       * <code>float terrainPosY = 4;</code>
       * @param value The terrainPosY to set.
       * @return This builder for chaining.
       */
      public Builder setTerrainPosY(float value) {
        
        terrainPosY_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float terrainPosY = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearTerrainPosY() {
        
        terrainPosY_ = 0F;
        onChanged();
        return this;
      }

      private int type_ = 0;
      /**
       * <code>.DnD.Terrain.TileItemDataType type = 5;</code>
       * @return The enum numeric value on the wire for type.
       */
      public int getTypeValue() {
        return type_;
      }
      /**
       * <code>.DnD.Terrain.TileItemDataType type = 5;</code>
       * @param value The enum numeric value on the wire for type to set.
       * @return This builder for chaining.
       */
      public Builder setTypeValue(int value) {
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.DnD.Terrain.TileItemDataType type = 5;</code>
       * @return The type.
       */
      public DnD.Terrain.TileItemDataOuterClass.TileItemDataType getType() {
        @SuppressWarnings("deprecation")
        DnD.Terrain.TileItemDataOuterClass.TileItemDataType result = DnD.Terrain.TileItemDataOuterClass.TileItemDataType.valueOf(type_);
        return result == null ? DnD.Terrain.TileItemDataOuterClass.TileItemDataType.UNRECOGNIZED : result;
      }
      /**
       * <code>.DnD.Terrain.TileItemDataType type = 5;</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(DnD.Terrain.TileItemDataOuterClass.TileItemDataType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.DnD.Terrain.TileItemDataType type = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:DnD.Terrain.TileItemData)
    }

    // @@protoc_insertion_point(class_scope:DnD.Terrain.TileItemData)
    private static final DnD.Terrain.TileItemDataOuterClass.TileItemData DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new DnD.Terrain.TileItemDataOuterClass.TileItemData();
    }

    public static DnD.Terrain.TileItemDataOuterClass.TileItemData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TileItemData>
        PARSER = new com.google.protobuf.AbstractParser<TileItemData>() {
      @java.lang.Override
      public TileItemData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TileItemData(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TileItemData> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TileItemData> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public DnD.Terrain.TileItemDataOuterClass.TileItemData getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DnD_Terrain_TileItemData_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DnD_Terrain_TileItemData_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022TileItemData.proto\022\013DnD.Terrain\"\201\001\n\014Ti" +
      "leItemData\022\014\n\004posX\030\001 \001(\002\022\014\n\004posY\030\002 \001(\002\022\023" +
      "\n\013terrainPosX\030\003 \001(\002\022\023\n\013terrainPosY\030\004 \001(\002" +
      "\022+\n\004type\030\005 \001(\0162\035.DnD.Terrain.TileItemDat" +
      "aType**\n\020TileItemDataType\022\n\n\006DELETE\020\000\022\n\n" +
      "\006UPDATE\020\001B\r\n\013DnD.Terrainb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_DnD_Terrain_TileItemData_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_DnD_Terrain_TileItemData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DnD_Terrain_TileItemData_descriptor,
        new java.lang.String[] { "PosX", "PosY", "TerrainPosX", "TerrainPosY", "Type", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
