// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NPCData.proto

package DnD.NPCs;

public final class NPCDataOuterClass {
  private NPCDataOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface NPCDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:DnD.NPCs.NPCData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>float health = 1;</code>
     * @return The health.
     */
    float getHealth();

    /**
     * <code>float posX = 2;</code>
     * @return The posX.
     */
    float getPosX();

    /**
     * <code>float posY = 3;</code>
     * @return The posY.
     */
    float getPosY();

    /**
     * <code>string npcID = 4;</code>
     * @return The npcID.
     */
    java.lang.String getNpcID();
    /**
     * <code>string npcID = 4;</code>
     * @return The bytes for npcID.
     */
    com.google.protobuf.ByteString
        getNpcIDBytes();
  }
  /**
   * Protobuf type {@code DnD.NPCs.NPCData}
   */
  public  static final class NPCData extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:DnD.NPCs.NPCData)
      NPCDataOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use NPCData.newBuilder() to construct.
    private NPCData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private NPCData() {
      npcID_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new NPCData();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private NPCData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 13: {

              health_ = input.readFloat();
              break;
            }
            case 21: {

              posX_ = input.readFloat();
              break;
            }
            case 29: {

              posY_ = input.readFloat();
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              npcID_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return DnD.NPCs.NPCDataOuterClass.internal_static_DnD_NPCs_NPCData_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return DnD.NPCs.NPCDataOuterClass.internal_static_DnD_NPCs_NPCData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              DnD.NPCs.NPCDataOuterClass.NPCData.class, DnD.NPCs.NPCDataOuterClass.NPCData.Builder.class);
    }

    public static final int HEALTH_FIELD_NUMBER = 1;
    private float health_;
    /**
     * <code>float health = 1;</code>
     * @return The health.
     */
    public float getHealth() {
      return health_;
    }

    public static final int POSX_FIELD_NUMBER = 2;
    private float posX_;
    /**
     * <code>float posX = 2;</code>
     * @return The posX.
     */
    public float getPosX() {
      return posX_;
    }

    public static final int POSY_FIELD_NUMBER = 3;
    private float posY_;
    /**
     * <code>float posY = 3;</code>
     * @return The posY.
     */
    public float getPosY() {
      return posY_;
    }

    public static final int NPCID_FIELD_NUMBER = 4;
    private volatile java.lang.Object npcID_;
    /**
     * <code>string npcID = 4;</code>
     * @return The npcID.
     */
    public java.lang.String getNpcID() {
      java.lang.Object ref = npcID_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        npcID_ = s;
        return s;
      }
    }
    /**
     * <code>string npcID = 4;</code>
     * @return The bytes for npcID.
     */
    public com.google.protobuf.ByteString
        getNpcIDBytes() {
      java.lang.Object ref = npcID_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        npcID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (health_ != 0F) {
        output.writeFloat(1, health_);
      }
      if (posX_ != 0F) {
        output.writeFloat(2, posX_);
      }
      if (posY_ != 0F) {
        output.writeFloat(3, posY_);
      }
      if (!getNpcIDBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, npcID_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (health_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(1, health_);
      }
      if (posX_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(2, posX_);
      }
      if (posY_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(3, posY_);
      }
      if (!getNpcIDBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, npcID_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof DnD.NPCs.NPCDataOuterClass.NPCData)) {
        return super.equals(obj);
      }
      DnD.NPCs.NPCDataOuterClass.NPCData other = (DnD.NPCs.NPCDataOuterClass.NPCData) obj;

      if (java.lang.Float.floatToIntBits(getHealth())
          != java.lang.Float.floatToIntBits(
              other.getHealth())) return false;
      if (java.lang.Float.floatToIntBits(getPosX())
          != java.lang.Float.floatToIntBits(
              other.getPosX())) return false;
      if (java.lang.Float.floatToIntBits(getPosY())
          != java.lang.Float.floatToIntBits(
              other.getPosY())) return false;
      if (!getNpcID()
          .equals(other.getNpcID())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + HEALTH_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getHealth());
      hash = (37 * hash) + POSX_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getPosX());
      hash = (37 * hash) + POSY_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getPosY());
      hash = (37 * hash) + NPCID_FIELD_NUMBER;
      hash = (53 * hash) + getNpcID().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static DnD.NPCs.NPCDataOuterClass.NPCData parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static DnD.NPCs.NPCDataOuterClass.NPCData parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static DnD.NPCs.NPCDataOuterClass.NPCData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static DnD.NPCs.NPCDataOuterClass.NPCData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static DnD.NPCs.NPCDataOuterClass.NPCData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static DnD.NPCs.NPCDataOuterClass.NPCData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static DnD.NPCs.NPCDataOuterClass.NPCData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static DnD.NPCs.NPCDataOuterClass.NPCData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static DnD.NPCs.NPCDataOuterClass.NPCData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static DnD.NPCs.NPCDataOuterClass.NPCData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static DnD.NPCs.NPCDataOuterClass.NPCData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static DnD.NPCs.NPCDataOuterClass.NPCData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(DnD.NPCs.NPCDataOuterClass.NPCData prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code DnD.NPCs.NPCData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:DnD.NPCs.NPCData)
        DnD.NPCs.NPCDataOuterClass.NPCDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return DnD.NPCs.NPCDataOuterClass.internal_static_DnD_NPCs_NPCData_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return DnD.NPCs.NPCDataOuterClass.internal_static_DnD_NPCs_NPCData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                DnD.NPCs.NPCDataOuterClass.NPCData.class, DnD.NPCs.NPCDataOuterClass.NPCData.Builder.class);
      }

      // Construct using DnD.NPCs.NPCDataOuterClass.NPCData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        health_ = 0F;

        posX_ = 0F;

        posY_ = 0F;

        npcID_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return DnD.NPCs.NPCDataOuterClass.internal_static_DnD_NPCs_NPCData_descriptor;
      }

      @java.lang.Override
      public DnD.NPCs.NPCDataOuterClass.NPCData getDefaultInstanceForType() {
        return DnD.NPCs.NPCDataOuterClass.NPCData.getDefaultInstance();
      }

      @java.lang.Override
      public DnD.NPCs.NPCDataOuterClass.NPCData build() {
        DnD.NPCs.NPCDataOuterClass.NPCData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public DnD.NPCs.NPCDataOuterClass.NPCData buildPartial() {
        DnD.NPCs.NPCDataOuterClass.NPCData result = new DnD.NPCs.NPCDataOuterClass.NPCData(this);
        result.health_ = health_;
        result.posX_ = posX_;
        result.posY_ = posY_;
        result.npcID_ = npcID_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof DnD.NPCs.NPCDataOuterClass.NPCData) {
          return mergeFrom((DnD.NPCs.NPCDataOuterClass.NPCData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(DnD.NPCs.NPCDataOuterClass.NPCData other) {
        if (other == DnD.NPCs.NPCDataOuterClass.NPCData.getDefaultInstance()) return this;
        if (other.getHealth() != 0F) {
          setHealth(other.getHealth());
        }
        if (other.getPosX() != 0F) {
          setPosX(other.getPosX());
        }
        if (other.getPosY() != 0F) {
          setPosY(other.getPosY());
        }
        if (!other.getNpcID().isEmpty()) {
          npcID_ = other.npcID_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        DnD.NPCs.NPCDataOuterClass.NPCData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (DnD.NPCs.NPCDataOuterClass.NPCData) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private float health_ ;
      /**
       * <code>float health = 1;</code>
       * @return The health.
       */
      public float getHealth() {
        return health_;
      }
      /**
       * <code>float health = 1;</code>
       * @param value The health to set.
       * @return This builder for chaining.
       */
      public Builder setHealth(float value) {
        
        health_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float health = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearHealth() {
        
        health_ = 0F;
        onChanged();
        return this;
      }

      private float posX_ ;
      /**
       * <code>float posX = 2;</code>
       * @return The posX.
       */
      public float getPosX() {
        return posX_;
      }
      /**
       * <code>float posX = 2;</code>
       * @param value The posX to set.
       * @return This builder for chaining.
       */
      public Builder setPosX(float value) {
        
        posX_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float posX = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearPosX() {
        
        posX_ = 0F;
        onChanged();
        return this;
      }

      private float posY_ ;
      /**
       * <code>float posY = 3;</code>
       * @return The posY.
       */
      public float getPosY() {
        return posY_;
      }
      /**
       * <code>float posY = 3;</code>
       * @param value The posY to set.
       * @return This builder for chaining.
       */
      public Builder setPosY(float value) {
        
        posY_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float posY = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearPosY() {
        
        posY_ = 0F;
        onChanged();
        return this;
      }

      private java.lang.Object npcID_ = "";
      /**
       * <code>string npcID = 4;</code>
       * @return The npcID.
       */
      public java.lang.String getNpcID() {
        java.lang.Object ref = npcID_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          npcID_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string npcID = 4;</code>
       * @return The bytes for npcID.
       */
      public com.google.protobuf.ByteString
          getNpcIDBytes() {
        java.lang.Object ref = npcID_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          npcID_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string npcID = 4;</code>
       * @param value The npcID to set.
       * @return This builder for chaining.
       */
      public Builder setNpcID(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        npcID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string npcID = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearNpcID() {
        
        npcID_ = getDefaultInstance().getNpcID();
        onChanged();
        return this;
      }
      /**
       * <code>string npcID = 4;</code>
       * @param value The bytes for npcID to set.
       * @return This builder for chaining.
       */
      public Builder setNpcIDBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        npcID_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:DnD.NPCs.NPCData)
    }

    // @@protoc_insertion_point(class_scope:DnD.NPCs.NPCData)
    private static final DnD.NPCs.NPCDataOuterClass.NPCData DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new DnD.NPCs.NPCDataOuterClass.NPCData();
    }

    public static DnD.NPCs.NPCDataOuterClass.NPCData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<NPCData>
        PARSER = new com.google.protobuf.AbstractParser<NPCData>() {
      @java.lang.Override
      public NPCData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new NPCData(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<NPCData> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<NPCData> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public DnD.NPCs.NPCDataOuterClass.NPCData getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DnD_NPCs_NPCData_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DnD_NPCs_NPCData_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rNPCData.proto\022\010DnD.NPCs\"D\n\007NPCData\022\016\n\006" +
      "health\030\001 \001(\002\022\014\n\004posX\030\002 \001(\002\022\014\n\004posY\030\003 \001(\002" +
      "\022\r\n\005npcID\030\004 \001(\tB\n\n\010DnD.NPCsb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_DnD_NPCs_NPCData_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_DnD_NPCs_NPCData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DnD_NPCs_NPCData_descriptor,
        new java.lang.String[] { "Health", "PosX", "PosY", "NpcID", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
