// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ClientRequest.proto

package DnD.service;

public final class ClientRequestOuterClass {
  private ClientRequestOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code DnD.service.ClientRequestType}
   */
  public enum ClientRequestType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>CLIENT_CONNECTION = 0;</code>
     */
    CLIENT_CONNECTION(0),
    /**
     * <code>CLIENT_DISCONNECTION = 1;</code>
     */
    CLIENT_DISCONNECTION(1),
    /**
     * <code>TILE_GENERATION = 2;</code>
     */
    TILE_GENERATION(2),
    /**
     * <code>CLIENT_UPDATE = 3;</code>
     */
    CLIENT_UPDATE(3),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>CLIENT_CONNECTION = 0;</code>
     */
    public static final int CLIENT_CONNECTION_VALUE = 0;
    /**
     * <code>CLIENT_DISCONNECTION = 1;</code>
     */
    public static final int CLIENT_DISCONNECTION_VALUE = 1;
    /**
     * <code>TILE_GENERATION = 2;</code>
     */
    public static final int TILE_GENERATION_VALUE = 2;
    /**
     * <code>CLIENT_UPDATE = 3;</code>
     */
    public static final int CLIENT_UPDATE_VALUE = 3;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ClientRequestType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static ClientRequestType forNumber(int value) {
      switch (value) {
        case 0: return CLIENT_CONNECTION;
        case 1: return CLIENT_DISCONNECTION;
        case 2: return TILE_GENERATION;
        case 3: return CLIENT_UPDATE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ClientRequestType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        ClientRequestType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ClientRequestType>() {
            public ClientRequestType findValueByNumber(int number) {
              return ClientRequestType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return DnD.service.ClientRequestOuterClass.getDescriptor().getEnumTypes().get(0);
    }

    private static final ClientRequestType[] VALUES = values();

    public static ClientRequestType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private ClientRequestType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:DnD.service.ClientRequestType)
  }

  public interface ClientRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:DnD.service.ClientRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.DnD.service.ClientRequestType reqType = 1;</code>
     * @return The enum numeric value on the wire for reqType.
     */
    int getReqTypeValue();
    /**
     * <code>.DnD.service.ClientRequestType reqType = 1;</code>
     * @return The reqType.
     */
    DnD.service.ClientRequestOuterClass.ClientRequestType getReqType();

    /**
     * <code>bytes requestData = 2;</code>
     * @return The requestData.
     */
    com.google.protobuf.ByteString getRequestData();
  }
  /**
   * Protobuf type {@code DnD.service.ClientRequest}
   */
  public  static final class ClientRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:DnD.service.ClientRequest)
      ClientRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ClientRequest.newBuilder() to construct.
    private ClientRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ClientRequest() {
      reqType_ = 0;
      requestData_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ClientRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ClientRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();

              reqType_ = rawValue;
              break;
            }
            case 18: {

              requestData_ = input.readBytes();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return DnD.service.ClientRequestOuterClass.internal_static_DnD_service_ClientRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return DnD.service.ClientRequestOuterClass.internal_static_DnD_service_ClientRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              DnD.service.ClientRequestOuterClass.ClientRequest.class, DnD.service.ClientRequestOuterClass.ClientRequest.Builder.class);
    }

    public static final int REQTYPE_FIELD_NUMBER = 1;
    private int reqType_;
    /**
     * <code>.DnD.service.ClientRequestType reqType = 1;</code>
     * @return The enum numeric value on the wire for reqType.
     */
    public int getReqTypeValue() {
      return reqType_;
    }
    /**
     * <code>.DnD.service.ClientRequestType reqType = 1;</code>
     * @return The reqType.
     */
    public DnD.service.ClientRequestOuterClass.ClientRequestType getReqType() {
      @SuppressWarnings("deprecation")
      DnD.service.ClientRequestOuterClass.ClientRequestType result = DnD.service.ClientRequestOuterClass.ClientRequestType.valueOf(reqType_);
      return result == null ? DnD.service.ClientRequestOuterClass.ClientRequestType.UNRECOGNIZED : result;
    }

    public static final int REQUESTDATA_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString requestData_;
    /**
     * <code>bytes requestData = 2;</code>
     * @return The requestData.
     */
    public com.google.protobuf.ByteString getRequestData() {
      return requestData_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (reqType_ != DnD.service.ClientRequestOuterClass.ClientRequestType.CLIENT_CONNECTION.getNumber()) {
        output.writeEnum(1, reqType_);
      }
      if (!requestData_.isEmpty()) {
        output.writeBytes(2, requestData_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (reqType_ != DnD.service.ClientRequestOuterClass.ClientRequestType.CLIENT_CONNECTION.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, reqType_);
      }
      if (!requestData_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, requestData_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof DnD.service.ClientRequestOuterClass.ClientRequest)) {
        return super.equals(obj);
      }
      DnD.service.ClientRequestOuterClass.ClientRequest other = (DnD.service.ClientRequestOuterClass.ClientRequest) obj;

      if (reqType_ != other.reqType_) return false;
      if (!getRequestData()
          .equals(other.getRequestData())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + REQTYPE_FIELD_NUMBER;
      hash = (53 * hash) + reqType_;
      hash = (37 * hash) + REQUESTDATA_FIELD_NUMBER;
      hash = (53 * hash) + getRequestData().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static DnD.service.ClientRequestOuterClass.ClientRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static DnD.service.ClientRequestOuterClass.ClientRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static DnD.service.ClientRequestOuterClass.ClientRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static DnD.service.ClientRequestOuterClass.ClientRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static DnD.service.ClientRequestOuterClass.ClientRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static DnD.service.ClientRequestOuterClass.ClientRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static DnD.service.ClientRequestOuterClass.ClientRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static DnD.service.ClientRequestOuterClass.ClientRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static DnD.service.ClientRequestOuterClass.ClientRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static DnD.service.ClientRequestOuterClass.ClientRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static DnD.service.ClientRequestOuterClass.ClientRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static DnD.service.ClientRequestOuterClass.ClientRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(DnD.service.ClientRequestOuterClass.ClientRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code DnD.service.ClientRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:DnD.service.ClientRequest)
        DnD.service.ClientRequestOuterClass.ClientRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return DnD.service.ClientRequestOuterClass.internal_static_DnD_service_ClientRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return DnD.service.ClientRequestOuterClass.internal_static_DnD_service_ClientRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                DnD.service.ClientRequestOuterClass.ClientRequest.class, DnD.service.ClientRequestOuterClass.ClientRequest.Builder.class);
      }

      // Construct using DnD.service.ClientRequestOuterClass.ClientRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        reqType_ = 0;

        requestData_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return DnD.service.ClientRequestOuterClass.internal_static_DnD_service_ClientRequest_descriptor;
      }

      @java.lang.Override
      public DnD.service.ClientRequestOuterClass.ClientRequest getDefaultInstanceForType() {
        return DnD.service.ClientRequestOuterClass.ClientRequest.getDefaultInstance();
      }

      @java.lang.Override
      public DnD.service.ClientRequestOuterClass.ClientRequest build() {
        DnD.service.ClientRequestOuterClass.ClientRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public DnD.service.ClientRequestOuterClass.ClientRequest buildPartial() {
        DnD.service.ClientRequestOuterClass.ClientRequest result = new DnD.service.ClientRequestOuterClass.ClientRequest(this);
        result.reqType_ = reqType_;
        result.requestData_ = requestData_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof DnD.service.ClientRequestOuterClass.ClientRequest) {
          return mergeFrom((DnD.service.ClientRequestOuterClass.ClientRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(DnD.service.ClientRequestOuterClass.ClientRequest other) {
        if (other == DnD.service.ClientRequestOuterClass.ClientRequest.getDefaultInstance()) return this;
        if (other.reqType_ != 0) {
          setReqTypeValue(other.getReqTypeValue());
        }
        if (other.getRequestData() != com.google.protobuf.ByteString.EMPTY) {
          setRequestData(other.getRequestData());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        DnD.service.ClientRequestOuterClass.ClientRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (DnD.service.ClientRequestOuterClass.ClientRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int reqType_ = 0;
      /**
       * <code>.DnD.service.ClientRequestType reqType = 1;</code>
       * @return The enum numeric value on the wire for reqType.
       */
      public int getReqTypeValue() {
        return reqType_;
      }
      /**
       * <code>.DnD.service.ClientRequestType reqType = 1;</code>
       * @param value The enum numeric value on the wire for reqType to set.
       * @return This builder for chaining.
       */
      public Builder setReqTypeValue(int value) {
        reqType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.DnD.service.ClientRequestType reqType = 1;</code>
       * @return The reqType.
       */
      public DnD.service.ClientRequestOuterClass.ClientRequestType getReqType() {
        @SuppressWarnings("deprecation")
        DnD.service.ClientRequestOuterClass.ClientRequestType result = DnD.service.ClientRequestOuterClass.ClientRequestType.valueOf(reqType_);
        return result == null ? DnD.service.ClientRequestOuterClass.ClientRequestType.UNRECOGNIZED : result;
      }
      /**
       * <code>.DnD.service.ClientRequestType reqType = 1;</code>
       * @param value The reqType to set.
       * @return This builder for chaining.
       */
      public Builder setReqType(DnD.service.ClientRequestOuterClass.ClientRequestType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        reqType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.DnD.service.ClientRequestType reqType = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearReqType() {
        
        reqType_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString requestData_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes requestData = 2;</code>
       * @return The requestData.
       */
      public com.google.protobuf.ByteString getRequestData() {
        return requestData_;
      }
      /**
       * <code>bytes requestData = 2;</code>
       * @param value The requestData to set.
       * @return This builder for chaining.
       */
      public Builder setRequestData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        requestData_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes requestData = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearRequestData() {
        
        requestData_ = getDefaultInstance().getRequestData();
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:DnD.service.ClientRequest)
    }

    // @@protoc_insertion_point(class_scope:DnD.service.ClientRequest)
    private static final DnD.service.ClientRequestOuterClass.ClientRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new DnD.service.ClientRequestOuterClass.ClientRequest();
    }

    public static DnD.service.ClientRequestOuterClass.ClientRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ClientRequest>
        PARSER = new com.google.protobuf.AbstractParser<ClientRequest>() {
      @java.lang.Override
      public ClientRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ClientRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ClientRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ClientRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public DnD.service.ClientRequestOuterClass.ClientRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DnD_service_ClientRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DnD_service_ClientRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023ClientRequest.proto\022\013DnD.service\"U\n\rCl" +
      "ientRequest\022/\n\007reqType\030\001 \001(\0162\036.DnD.servi" +
      "ce.ClientRequestType\022\023\n\013requestData\030\002 \001(" +
      "\014*l\n\021ClientRequestType\022\025\n\021CLIENT_CONNECT" +
      "ION\020\000\022\030\n\024CLIENT_DISCONNECTION\020\001\022\023\n\017TILE_" +
      "GENERATION\020\002\022\021\n\rCLIENT_UPDATE\020\003B&\n\013DnD.s" +
      "erviceB\027ClientRequestOuterClassb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_DnD_service_ClientRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_DnD_service_ClientRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DnD_service_ClientRequest_descriptor,
        new java.lang.String[] { "ReqType", "RequestData", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
