// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Client.proto

package DnD.service;

public final class ClientOuterClass {
  private ClientOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ClientOrBuilder extends
      // @@protoc_insertion_point(interface_extends:DnD.service.Client)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 portNumber = 1;</code>
     * @return The portNumber.
     */
    int getPortNumber();

    /**
     * <code>string localAddress = 2;</code>
     * @return The localAddress.
     */
    java.lang.String getLocalAddress();
    /**
     * <code>string localAddress = 2;</code>
     * @return The bytes for localAddress.
     */
    com.google.protobuf.ByteString
        getLocalAddressBytes();

    /**
     * <code>string clientID = 3;</code>
     * @return The clientID.
     */
    java.lang.String getClientID();
    /**
     * <code>string clientID = 3;</code>
     * @return The bytes for clientID.
     */
    com.google.protobuf.ByteString
        getClientIDBytes();

    /**
     * <code>.DnD.Player.Player player = 4;</code>
     * @return Whether the player field is set.
     */
    boolean hasPlayer();
    /**
     * <code>.DnD.Player.Player player = 4;</code>
     * @return The player.
     */
    DnD.Player.PlayerOuterClass.Player getPlayer();
    /**
     * <code>.DnD.Player.Player player = 4;</code>
     */
    DnD.Player.PlayerOuterClass.PlayerOrBuilder getPlayerOrBuilder();
  }
  /**
   * Protobuf type {@code DnD.service.Client}
   */
  public  static final class Client extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:DnD.service.Client)
      ClientOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Client.newBuilder() to construct.
    private Client(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Client() {
      localAddress_ = "";
      clientID_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Client();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Client(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              portNumber_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              localAddress_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              clientID_ = s;
              break;
            }
            case 34: {
              DnD.Player.PlayerOuterClass.Player.Builder subBuilder = null;
              if (player_ != null) {
                subBuilder = player_.toBuilder();
              }
              player_ = input.readMessage(DnD.Player.PlayerOuterClass.Player.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(player_);
                player_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return DnD.service.ClientOuterClass.internal_static_DnD_service_Client_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return DnD.service.ClientOuterClass.internal_static_DnD_service_Client_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              DnD.service.ClientOuterClass.Client.class, DnD.service.ClientOuterClass.Client.Builder.class);
    }

    public static final int PORTNUMBER_FIELD_NUMBER = 1;
    private int portNumber_;
    /**
     * <code>int32 portNumber = 1;</code>
     * @return The portNumber.
     */
    public int getPortNumber() {
      return portNumber_;
    }

    public static final int LOCALADDRESS_FIELD_NUMBER = 2;
    private volatile java.lang.Object localAddress_;
    /**
     * <code>string localAddress = 2;</code>
     * @return The localAddress.
     */
    public java.lang.String getLocalAddress() {
      java.lang.Object ref = localAddress_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        localAddress_ = s;
        return s;
      }
    }
    /**
     * <code>string localAddress = 2;</code>
     * @return The bytes for localAddress.
     */
    public com.google.protobuf.ByteString
        getLocalAddressBytes() {
      java.lang.Object ref = localAddress_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        localAddress_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CLIENTID_FIELD_NUMBER = 3;
    private volatile java.lang.Object clientID_;
    /**
     * <code>string clientID = 3;</code>
     * @return The clientID.
     */
    public java.lang.String getClientID() {
      java.lang.Object ref = clientID_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        clientID_ = s;
        return s;
      }
    }
    /**
     * <code>string clientID = 3;</code>
     * @return The bytes for clientID.
     */
    public com.google.protobuf.ByteString
        getClientIDBytes() {
      java.lang.Object ref = clientID_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        clientID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PLAYER_FIELD_NUMBER = 4;
    private DnD.Player.PlayerOuterClass.Player player_;
    /**
     * <code>.DnD.Player.Player player = 4;</code>
     * @return Whether the player field is set.
     */
    public boolean hasPlayer() {
      return player_ != null;
    }
    /**
     * <code>.DnD.Player.Player player = 4;</code>
     * @return The player.
     */
    public DnD.Player.PlayerOuterClass.Player getPlayer() {
      return player_ == null ? DnD.Player.PlayerOuterClass.Player.getDefaultInstance() : player_;
    }
    /**
     * <code>.DnD.Player.Player player = 4;</code>
     */
    public DnD.Player.PlayerOuterClass.PlayerOrBuilder getPlayerOrBuilder() {
      return getPlayer();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (portNumber_ != 0) {
        output.writeInt32(1, portNumber_);
      }
      if (!getLocalAddressBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, localAddress_);
      }
      if (!getClientIDBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, clientID_);
      }
      if (player_ != null) {
        output.writeMessage(4, getPlayer());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (portNumber_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, portNumber_);
      }
      if (!getLocalAddressBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, localAddress_);
      }
      if (!getClientIDBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, clientID_);
      }
      if (player_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getPlayer());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof DnD.service.ClientOuterClass.Client)) {
        return super.equals(obj);
      }
      DnD.service.ClientOuterClass.Client other = (DnD.service.ClientOuterClass.Client) obj;

      if (getPortNumber()
          != other.getPortNumber()) return false;
      if (!getLocalAddress()
          .equals(other.getLocalAddress())) return false;
      if (!getClientID()
          .equals(other.getClientID())) return false;
      if (hasPlayer() != other.hasPlayer()) return false;
      if (hasPlayer()) {
        if (!getPlayer()
            .equals(other.getPlayer())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + PORTNUMBER_FIELD_NUMBER;
      hash = (53 * hash) + getPortNumber();
      hash = (37 * hash) + LOCALADDRESS_FIELD_NUMBER;
      hash = (53 * hash) + getLocalAddress().hashCode();
      hash = (37 * hash) + CLIENTID_FIELD_NUMBER;
      hash = (53 * hash) + getClientID().hashCode();
      if (hasPlayer()) {
        hash = (37 * hash) + PLAYER_FIELD_NUMBER;
        hash = (53 * hash) + getPlayer().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static DnD.service.ClientOuterClass.Client parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static DnD.service.ClientOuterClass.Client parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static DnD.service.ClientOuterClass.Client parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static DnD.service.ClientOuterClass.Client parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static DnD.service.ClientOuterClass.Client parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static DnD.service.ClientOuterClass.Client parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static DnD.service.ClientOuterClass.Client parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static DnD.service.ClientOuterClass.Client parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static DnD.service.ClientOuterClass.Client parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static DnD.service.ClientOuterClass.Client parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static DnD.service.ClientOuterClass.Client parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static DnD.service.ClientOuterClass.Client parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(DnD.service.ClientOuterClass.Client prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code DnD.service.Client}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:DnD.service.Client)
        DnD.service.ClientOuterClass.ClientOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return DnD.service.ClientOuterClass.internal_static_DnD_service_Client_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return DnD.service.ClientOuterClass.internal_static_DnD_service_Client_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                DnD.service.ClientOuterClass.Client.class, DnD.service.ClientOuterClass.Client.Builder.class);
      }

      // Construct using DnD.service.ClientOuterClass.Client.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        portNumber_ = 0;

        localAddress_ = "";

        clientID_ = "";

        if (playerBuilder_ == null) {
          player_ = null;
        } else {
          player_ = null;
          playerBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return DnD.service.ClientOuterClass.internal_static_DnD_service_Client_descriptor;
      }

      @java.lang.Override
      public DnD.service.ClientOuterClass.Client getDefaultInstanceForType() {
        return DnD.service.ClientOuterClass.Client.getDefaultInstance();
      }

      @java.lang.Override
      public DnD.service.ClientOuterClass.Client build() {
        DnD.service.ClientOuterClass.Client result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public DnD.service.ClientOuterClass.Client buildPartial() {
        DnD.service.ClientOuterClass.Client result = new DnD.service.ClientOuterClass.Client(this);
        result.portNumber_ = portNumber_;
        result.localAddress_ = localAddress_;
        result.clientID_ = clientID_;
        if (playerBuilder_ == null) {
          result.player_ = player_;
        } else {
          result.player_ = playerBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof DnD.service.ClientOuterClass.Client) {
          return mergeFrom((DnD.service.ClientOuterClass.Client)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(DnD.service.ClientOuterClass.Client other) {
        if (other == DnD.service.ClientOuterClass.Client.getDefaultInstance()) return this;
        if (other.getPortNumber() != 0) {
          setPortNumber(other.getPortNumber());
        }
        if (!other.getLocalAddress().isEmpty()) {
          localAddress_ = other.localAddress_;
          onChanged();
        }
        if (!other.getClientID().isEmpty()) {
          clientID_ = other.clientID_;
          onChanged();
        }
        if (other.hasPlayer()) {
          mergePlayer(other.getPlayer());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        DnD.service.ClientOuterClass.Client parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (DnD.service.ClientOuterClass.Client) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int portNumber_ ;
      /**
       * <code>int32 portNumber = 1;</code>
       * @return The portNumber.
       */
      public int getPortNumber() {
        return portNumber_;
      }
      /**
       * <code>int32 portNumber = 1;</code>
       * @param value The portNumber to set.
       * @return This builder for chaining.
       */
      public Builder setPortNumber(int value) {
        
        portNumber_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 portNumber = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearPortNumber() {
        
        portNumber_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object localAddress_ = "";
      /**
       * <code>string localAddress = 2;</code>
       * @return The localAddress.
       */
      public java.lang.String getLocalAddress() {
        java.lang.Object ref = localAddress_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          localAddress_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string localAddress = 2;</code>
       * @return The bytes for localAddress.
       */
      public com.google.protobuf.ByteString
          getLocalAddressBytes() {
        java.lang.Object ref = localAddress_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          localAddress_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string localAddress = 2;</code>
       * @param value The localAddress to set.
       * @return This builder for chaining.
       */
      public Builder setLocalAddress(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        localAddress_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string localAddress = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearLocalAddress() {
        
        localAddress_ = getDefaultInstance().getLocalAddress();
        onChanged();
        return this;
      }
      /**
       * <code>string localAddress = 2;</code>
       * @param value The bytes for localAddress to set.
       * @return This builder for chaining.
       */
      public Builder setLocalAddressBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        localAddress_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object clientID_ = "";
      /**
       * <code>string clientID = 3;</code>
       * @return The clientID.
       */
      public java.lang.String getClientID() {
        java.lang.Object ref = clientID_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          clientID_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string clientID = 3;</code>
       * @return The bytes for clientID.
       */
      public com.google.protobuf.ByteString
          getClientIDBytes() {
        java.lang.Object ref = clientID_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          clientID_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string clientID = 3;</code>
       * @param value The clientID to set.
       * @return This builder for chaining.
       */
      public Builder setClientID(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        clientID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string clientID = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearClientID() {
        
        clientID_ = getDefaultInstance().getClientID();
        onChanged();
        return this;
      }
      /**
       * <code>string clientID = 3;</code>
       * @param value The bytes for clientID to set.
       * @return This builder for chaining.
       */
      public Builder setClientIDBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        clientID_ = value;
        onChanged();
        return this;
      }

      private DnD.Player.PlayerOuterClass.Player player_;
      private com.google.protobuf.SingleFieldBuilderV3<
          DnD.Player.PlayerOuterClass.Player, DnD.Player.PlayerOuterClass.Player.Builder, DnD.Player.PlayerOuterClass.PlayerOrBuilder> playerBuilder_;
      /**
       * <code>.DnD.Player.Player player = 4;</code>
       * @return Whether the player field is set.
       */
      public boolean hasPlayer() {
        return playerBuilder_ != null || player_ != null;
      }
      /**
       * <code>.DnD.Player.Player player = 4;</code>
       * @return The player.
       */
      public DnD.Player.PlayerOuterClass.Player getPlayer() {
        if (playerBuilder_ == null) {
          return player_ == null ? DnD.Player.PlayerOuterClass.Player.getDefaultInstance() : player_;
        } else {
          return playerBuilder_.getMessage();
        }
      }
      /**
       * <code>.DnD.Player.Player player = 4;</code>
       */
      public Builder setPlayer(DnD.Player.PlayerOuterClass.Player value) {
        if (playerBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          player_ = value;
          onChanged();
        } else {
          playerBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.DnD.Player.Player player = 4;</code>
       */
      public Builder setPlayer(
          DnD.Player.PlayerOuterClass.Player.Builder builderForValue) {
        if (playerBuilder_ == null) {
          player_ = builderForValue.build();
          onChanged();
        } else {
          playerBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.DnD.Player.Player player = 4;</code>
       */
      public Builder mergePlayer(DnD.Player.PlayerOuterClass.Player value) {
        if (playerBuilder_ == null) {
          if (player_ != null) {
            player_ =
              DnD.Player.PlayerOuterClass.Player.newBuilder(player_).mergeFrom(value).buildPartial();
          } else {
            player_ = value;
          }
          onChanged();
        } else {
          playerBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.DnD.Player.Player player = 4;</code>
       */
      public Builder clearPlayer() {
        if (playerBuilder_ == null) {
          player_ = null;
          onChanged();
        } else {
          player_ = null;
          playerBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.DnD.Player.Player player = 4;</code>
       */
      public DnD.Player.PlayerOuterClass.Player.Builder getPlayerBuilder() {
        
        onChanged();
        return getPlayerFieldBuilder().getBuilder();
      }
      /**
       * <code>.DnD.Player.Player player = 4;</code>
       */
      public DnD.Player.PlayerOuterClass.PlayerOrBuilder getPlayerOrBuilder() {
        if (playerBuilder_ != null) {
          return playerBuilder_.getMessageOrBuilder();
        } else {
          return player_ == null ?
              DnD.Player.PlayerOuterClass.Player.getDefaultInstance() : player_;
        }
      }
      /**
       * <code>.DnD.Player.Player player = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          DnD.Player.PlayerOuterClass.Player, DnD.Player.PlayerOuterClass.Player.Builder, DnD.Player.PlayerOuterClass.PlayerOrBuilder> 
          getPlayerFieldBuilder() {
        if (playerBuilder_ == null) {
          playerBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              DnD.Player.PlayerOuterClass.Player, DnD.Player.PlayerOuterClass.Player.Builder, DnD.Player.PlayerOuterClass.PlayerOrBuilder>(
                  getPlayer(),
                  getParentForChildren(),
                  isClean());
          player_ = null;
        }
        return playerBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:DnD.service.Client)
    }

    // @@protoc_insertion_point(class_scope:DnD.service.Client)
    private static final DnD.service.ClientOuterClass.Client DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new DnD.service.ClientOuterClass.Client();
    }

    public static DnD.service.ClientOuterClass.Client getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Client>
        PARSER = new com.google.protobuf.AbstractParser<Client>() {
      @java.lang.Override
      public Client parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Client(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Client> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Client> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public DnD.service.ClientOuterClass.Client getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DnD_service_Client_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DnD_service_Client_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014Client.proto\022\013DnD.service\032\014Player.prot" +
      "o\"h\n\006Client\022\022\n\nportNumber\030\001 \001(\005\022\024\n\014local" +
      "Address\030\002 \001(\t\022\020\n\010clientID\030\003 \001(\t\022\"\n\006playe" +
      "r\030\004 \001(\0132\022.DnD.Player.PlayerB\037\n\013DnD.servi" +
      "ceB\020ClientOuterClassb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          DnD.Player.PlayerOuterClass.getDescriptor(),
        });
    internal_static_DnD_service_Client_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_DnD_service_Client_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DnD_service_Client_descriptor,
        new java.lang.String[] { "PortNumber", "LocalAddress", "ClientID", "Player", });
    DnD.Player.PlayerOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
