// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/ServerResponse.proto

package DnD.service;

public final class ServerResponseOuterClass {
  private ServerResponseOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code DnD.service.ServerResponseType}
   */
  public enum ServerResponseType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>CONNECTION_SUCCESS = 0;</code>
     */
    CONNECTION_SUCCESS(0),
    /**
     * <code>CONNECTION_FAILURE = 1;</code>
     */
    CONNECTION_FAILURE(1),
    /**
     * <code>TILE_GENERATION_RESPONSE = 2;</code>
     */
    TILE_GENERATION_RESPONSE(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>CONNECTION_SUCCESS = 0;</code>
     */
    public static final int CONNECTION_SUCCESS_VALUE = 0;
    /**
     * <code>CONNECTION_FAILURE = 1;</code>
     */
    public static final int CONNECTION_FAILURE_VALUE = 1;
    /**
     * <code>TILE_GENERATION_RESPONSE = 2;</code>
     */
    public static final int TILE_GENERATION_RESPONSE_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ServerResponseType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static ServerResponseType forNumber(int value) {
      switch (value) {
        case 0: return CONNECTION_SUCCESS;
        case 1: return CONNECTION_FAILURE;
        case 2: return TILE_GENERATION_RESPONSE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ServerResponseType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        ServerResponseType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ServerResponseType>() {
            public ServerResponseType findValueByNumber(int number) {
              return ServerResponseType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return DnD.service.ServerResponseOuterClass.getDescriptor().getEnumTypes().get(0);
    }

    private static final ServerResponseType[] VALUES = values();

    public static ServerResponseType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private ServerResponseType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:DnD.service.ServerResponseType)
  }

  public interface ServerResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:DnD.service.ServerResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.DnD.service.ServerResponseType response = 1;</code>
     * @return The enum numeric value on the wire for response.
     */
    int getResponseValue();
    /**
     * <code>.DnD.service.ServerResponseType response = 1;</code>
     * @return The response.
     */
    DnD.service.ServerResponseOuterClass.ServerResponseType getResponse();

    /**
     * <code>bytes responseData = 2;</code>
     * @return The responseData.
     */
    com.google.protobuf.ByteString getResponseData();
  }
  /**
   * Protobuf type {@code DnD.service.ServerResponse}
   */
  public  static final class ServerResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:DnD.service.ServerResponse)
      ServerResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ServerResponse.newBuilder() to construct.
    private ServerResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ServerResponse() {
      response_ = 0;
      responseData_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ServerResponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ServerResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();

              response_ = rawValue;
              break;
            }
            case 18: {

              responseData_ = input.readBytes();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return DnD.service.ServerResponseOuterClass.internal_static_DnD_service_ServerResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return DnD.service.ServerResponseOuterClass.internal_static_DnD_service_ServerResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              DnD.service.ServerResponseOuterClass.ServerResponse.class, DnD.service.ServerResponseOuterClass.ServerResponse.Builder.class);
    }

    public static final int RESPONSE_FIELD_NUMBER = 1;
    private int response_;
    /**
     * <code>.DnD.service.ServerResponseType response = 1;</code>
     * @return The enum numeric value on the wire for response.
     */
    public int getResponseValue() {
      return response_;
    }
    /**
     * <code>.DnD.service.ServerResponseType response = 1;</code>
     * @return The response.
     */
    public DnD.service.ServerResponseOuterClass.ServerResponseType getResponse() {
      @SuppressWarnings("deprecation")
      DnD.service.ServerResponseOuterClass.ServerResponseType result = DnD.service.ServerResponseOuterClass.ServerResponseType.valueOf(response_);
      return result == null ? DnD.service.ServerResponseOuterClass.ServerResponseType.UNRECOGNIZED : result;
    }

    public static final int RESPONSEDATA_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString responseData_;
    /**
     * <code>bytes responseData = 2;</code>
     * @return The responseData.
     */
    public com.google.protobuf.ByteString getResponseData() {
      return responseData_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (response_ != DnD.service.ServerResponseOuterClass.ServerResponseType.CONNECTION_SUCCESS.getNumber()) {
        output.writeEnum(1, response_);
      }
      if (!responseData_.isEmpty()) {
        output.writeBytes(2, responseData_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (response_ != DnD.service.ServerResponseOuterClass.ServerResponseType.CONNECTION_SUCCESS.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, response_);
      }
      if (!responseData_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, responseData_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof DnD.service.ServerResponseOuterClass.ServerResponse)) {
        return super.equals(obj);
      }
      DnD.service.ServerResponseOuterClass.ServerResponse other = (DnD.service.ServerResponseOuterClass.ServerResponse) obj;

      if (response_ != other.response_) return false;
      if (!getResponseData()
          .equals(other.getResponseData())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + RESPONSE_FIELD_NUMBER;
      hash = (53 * hash) + response_;
      hash = (37 * hash) + RESPONSEDATA_FIELD_NUMBER;
      hash = (53 * hash) + getResponseData().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static DnD.service.ServerResponseOuterClass.ServerResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static DnD.service.ServerResponseOuterClass.ServerResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static DnD.service.ServerResponseOuterClass.ServerResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static DnD.service.ServerResponseOuterClass.ServerResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static DnD.service.ServerResponseOuterClass.ServerResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static DnD.service.ServerResponseOuterClass.ServerResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static DnD.service.ServerResponseOuterClass.ServerResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static DnD.service.ServerResponseOuterClass.ServerResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static DnD.service.ServerResponseOuterClass.ServerResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static DnD.service.ServerResponseOuterClass.ServerResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static DnD.service.ServerResponseOuterClass.ServerResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static DnD.service.ServerResponseOuterClass.ServerResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(DnD.service.ServerResponseOuterClass.ServerResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code DnD.service.ServerResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:DnD.service.ServerResponse)
        DnD.service.ServerResponseOuterClass.ServerResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return DnD.service.ServerResponseOuterClass.internal_static_DnD_service_ServerResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return DnD.service.ServerResponseOuterClass.internal_static_DnD_service_ServerResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                DnD.service.ServerResponseOuterClass.ServerResponse.class, DnD.service.ServerResponseOuterClass.ServerResponse.Builder.class);
      }

      // Construct using DnD.service.ServerResponseOuterClass.ServerResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        response_ = 0;

        responseData_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return DnD.service.ServerResponseOuterClass.internal_static_DnD_service_ServerResponse_descriptor;
      }

      @java.lang.Override
      public DnD.service.ServerResponseOuterClass.ServerResponse getDefaultInstanceForType() {
        return DnD.service.ServerResponseOuterClass.ServerResponse.getDefaultInstance();
      }

      @java.lang.Override
      public DnD.service.ServerResponseOuterClass.ServerResponse build() {
        DnD.service.ServerResponseOuterClass.ServerResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public DnD.service.ServerResponseOuterClass.ServerResponse buildPartial() {
        DnD.service.ServerResponseOuterClass.ServerResponse result = new DnD.service.ServerResponseOuterClass.ServerResponse(this);
        result.response_ = response_;
        result.responseData_ = responseData_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof DnD.service.ServerResponseOuterClass.ServerResponse) {
          return mergeFrom((DnD.service.ServerResponseOuterClass.ServerResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(DnD.service.ServerResponseOuterClass.ServerResponse other) {
        if (other == DnD.service.ServerResponseOuterClass.ServerResponse.getDefaultInstance()) return this;
        if (other.response_ != 0) {
          setResponseValue(other.getResponseValue());
        }
        if (other.getResponseData() != com.google.protobuf.ByteString.EMPTY) {
          setResponseData(other.getResponseData());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        DnD.service.ServerResponseOuterClass.ServerResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (DnD.service.ServerResponseOuterClass.ServerResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int response_ = 0;
      /**
       * <code>.DnD.service.ServerResponseType response = 1;</code>
       * @return The enum numeric value on the wire for response.
       */
      public int getResponseValue() {
        return response_;
      }
      /**
       * <code>.DnD.service.ServerResponseType response = 1;</code>
       * @param value The enum numeric value on the wire for response to set.
       * @return This builder for chaining.
       */
      public Builder setResponseValue(int value) {
        response_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.DnD.service.ServerResponseType response = 1;</code>
       * @return The response.
       */
      public DnD.service.ServerResponseOuterClass.ServerResponseType getResponse() {
        @SuppressWarnings("deprecation")
        DnD.service.ServerResponseOuterClass.ServerResponseType result = DnD.service.ServerResponseOuterClass.ServerResponseType.valueOf(response_);
        return result == null ? DnD.service.ServerResponseOuterClass.ServerResponseType.UNRECOGNIZED : result;
      }
      /**
       * <code>.DnD.service.ServerResponseType response = 1;</code>
       * @param value The response to set.
       * @return This builder for chaining.
       */
      public Builder setResponse(DnD.service.ServerResponseOuterClass.ServerResponseType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        response_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.DnD.service.ServerResponseType response = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearResponse() {
        
        response_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString responseData_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes responseData = 2;</code>
       * @return The responseData.
       */
      public com.google.protobuf.ByteString getResponseData() {
        return responseData_;
      }
      /**
       * <code>bytes responseData = 2;</code>
       * @param value The responseData to set.
       * @return This builder for chaining.
       */
      public Builder setResponseData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        responseData_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes responseData = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearResponseData() {
        
        responseData_ = getDefaultInstance().getResponseData();
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:DnD.service.ServerResponse)
    }

    // @@protoc_insertion_point(class_scope:DnD.service.ServerResponse)
    private static final DnD.service.ServerResponseOuterClass.ServerResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new DnD.service.ServerResponseOuterClass.ServerResponse();
    }

    public static DnD.service.ServerResponseOuterClass.ServerResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ServerResponse>
        PARSER = new com.google.protobuf.AbstractParser<ServerResponse>() {
      @java.lang.Override
      public ServerResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ServerResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ServerResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ServerResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public DnD.service.ServerResponseOuterClass.ServerResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DnD_service_ServerResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DnD_service_ServerResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032proto/ServerResponse.proto\022\013DnD.servic" +
      "e\"Y\n\016ServerResponse\0221\n\010response\030\001 \001(\0162\037." +
      "DnD.service.ServerResponseType\022\024\n\014respon" +
      "seData\030\002 \001(\014*b\n\022ServerResponseType\022\026\n\022CO" +
      "NNECTION_SUCCESS\020\000\022\026\n\022CONNECTION_FAILURE" +
      "\020\001\022\034\n\030TILE_GENERATION_RESPONSE\020\002b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_DnD_service_ServerResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_DnD_service_ServerResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DnD_service_ServerResponse_descriptor,
        new java.lang.String[] { "Response", "ResponseData", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
