// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Player.proto

package DnD.Player;

public final class PlayerOuterClass {
  private PlayerOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PlayerOrBuilder extends
      // @@protoc_insertion_point(interface_extends:DnD.Player.Player)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>float posX = 1;</code>
     * @return The posX.
     */
    float getPosX();

    /**
     * <code>float posY = 2;</code>
     * @return The posY.
     */
    float getPosY();

    /**
     * <code>int32 viewDistance = 3;</code>
     * @return The viewDistance.
     */
    int getViewDistance();

    /**
     * <code>float currentTerrainPosX = 4;</code>
     * @return The currentTerrainPosX.
     */
    float getCurrentTerrainPosX();

    /**
     * <code>float currentTerrainPosY = 5;</code>
     * @return The currentTerrainPosY.
     */
    float getCurrentTerrainPosY();

    /**
     * <code>.DnD.Player.TerrainData terrainData = 6;</code>
     * @return Whether the terrainData field is set.
     */
    boolean hasTerrainData();
    /**
     * <code>.DnD.Player.TerrainData terrainData = 6;</code>
     * @return The terrainData.
     */
    DnD.Player.PlayerOuterClass.TerrainData getTerrainData();
    /**
     * <code>.DnD.Player.TerrainData terrainData = 6;</code>
     */
    DnD.Player.PlayerOuterClass.TerrainDataOrBuilder getTerrainDataOrBuilder();
  }
  /**
   * Protobuf type {@code DnD.Player.Player}
   */
  public  static final class Player extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:DnD.Player.Player)
      PlayerOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Player.newBuilder() to construct.
    private Player(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Player() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Player();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Player(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 13: {

              posX_ = input.readFloat();
              break;
            }
            case 21: {

              posY_ = input.readFloat();
              break;
            }
            case 24: {

              viewDistance_ = input.readInt32();
              break;
            }
            case 37: {

              currentTerrainPosX_ = input.readFloat();
              break;
            }
            case 45: {

              currentTerrainPosY_ = input.readFloat();
              break;
            }
            case 50: {
              DnD.Player.PlayerOuterClass.TerrainData.Builder subBuilder = null;
              if (terrainData_ != null) {
                subBuilder = terrainData_.toBuilder();
              }
              terrainData_ = input.readMessage(DnD.Player.PlayerOuterClass.TerrainData.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(terrainData_);
                terrainData_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return DnD.Player.PlayerOuterClass.internal_static_DnD_Player_Player_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return DnD.Player.PlayerOuterClass.internal_static_DnD_Player_Player_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              DnD.Player.PlayerOuterClass.Player.class, DnD.Player.PlayerOuterClass.Player.Builder.class);
    }

    public static final int POSX_FIELD_NUMBER = 1;
    private float posX_;
    /**
     * <code>float posX = 1;</code>
     * @return The posX.
     */
    public float getPosX() {
      return posX_;
    }

    public static final int POSY_FIELD_NUMBER = 2;
    private float posY_;
    /**
     * <code>float posY = 2;</code>
     * @return The posY.
     */
    public float getPosY() {
      return posY_;
    }

    public static final int VIEWDISTANCE_FIELD_NUMBER = 3;
    private int viewDistance_;
    /**
     * <code>int32 viewDistance = 3;</code>
     * @return The viewDistance.
     */
    public int getViewDistance() {
      return viewDistance_;
    }

    public static final int CURRENTTERRAINPOSX_FIELD_NUMBER = 4;
    private float currentTerrainPosX_;
    /**
     * <code>float currentTerrainPosX = 4;</code>
     * @return The currentTerrainPosX.
     */
    public float getCurrentTerrainPosX() {
      return currentTerrainPosX_;
    }

    public static final int CURRENTTERRAINPOSY_FIELD_NUMBER = 5;
    private float currentTerrainPosY_;
    /**
     * <code>float currentTerrainPosY = 5;</code>
     * @return The currentTerrainPosY.
     */
    public float getCurrentTerrainPosY() {
      return currentTerrainPosY_;
    }

    public static final int TERRAINDATA_FIELD_NUMBER = 6;
    private DnD.Player.PlayerOuterClass.TerrainData terrainData_;
    /**
     * <code>.DnD.Player.TerrainData terrainData = 6;</code>
     * @return Whether the terrainData field is set.
     */
    public boolean hasTerrainData() {
      return terrainData_ != null;
    }
    /**
     * <code>.DnD.Player.TerrainData terrainData = 6;</code>
     * @return The terrainData.
     */
    public DnD.Player.PlayerOuterClass.TerrainData getTerrainData() {
      return terrainData_ == null ? DnD.Player.PlayerOuterClass.TerrainData.getDefaultInstance() : terrainData_;
    }
    /**
     * <code>.DnD.Player.TerrainData terrainData = 6;</code>
     */
    public DnD.Player.PlayerOuterClass.TerrainDataOrBuilder getTerrainDataOrBuilder() {
      return getTerrainData();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (posX_ != 0F) {
        output.writeFloat(1, posX_);
      }
      if (posY_ != 0F) {
        output.writeFloat(2, posY_);
      }
      if (viewDistance_ != 0) {
        output.writeInt32(3, viewDistance_);
      }
      if (currentTerrainPosX_ != 0F) {
        output.writeFloat(4, currentTerrainPosX_);
      }
      if (currentTerrainPosY_ != 0F) {
        output.writeFloat(5, currentTerrainPosY_);
      }
      if (terrainData_ != null) {
        output.writeMessage(6, getTerrainData());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (posX_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(1, posX_);
      }
      if (posY_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(2, posY_);
      }
      if (viewDistance_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, viewDistance_);
      }
      if (currentTerrainPosX_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(4, currentTerrainPosX_);
      }
      if (currentTerrainPosY_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(5, currentTerrainPosY_);
      }
      if (terrainData_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, getTerrainData());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof DnD.Player.PlayerOuterClass.Player)) {
        return super.equals(obj);
      }
      DnD.Player.PlayerOuterClass.Player other = (DnD.Player.PlayerOuterClass.Player) obj;

      if (java.lang.Float.floatToIntBits(getPosX())
          != java.lang.Float.floatToIntBits(
              other.getPosX())) return false;
      if (java.lang.Float.floatToIntBits(getPosY())
          != java.lang.Float.floatToIntBits(
              other.getPosY())) return false;
      if (getViewDistance()
          != other.getViewDistance()) return false;
      if (java.lang.Float.floatToIntBits(getCurrentTerrainPosX())
          != java.lang.Float.floatToIntBits(
              other.getCurrentTerrainPosX())) return false;
      if (java.lang.Float.floatToIntBits(getCurrentTerrainPosY())
          != java.lang.Float.floatToIntBits(
              other.getCurrentTerrainPosY())) return false;
      if (hasTerrainData() != other.hasTerrainData()) return false;
      if (hasTerrainData()) {
        if (!getTerrainData()
            .equals(other.getTerrainData())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + POSX_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getPosX());
      hash = (37 * hash) + POSY_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getPosY());
      hash = (37 * hash) + VIEWDISTANCE_FIELD_NUMBER;
      hash = (53 * hash) + getViewDistance();
      hash = (37 * hash) + CURRENTTERRAINPOSX_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getCurrentTerrainPosX());
      hash = (37 * hash) + CURRENTTERRAINPOSY_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getCurrentTerrainPosY());
      if (hasTerrainData()) {
        hash = (37 * hash) + TERRAINDATA_FIELD_NUMBER;
        hash = (53 * hash) + getTerrainData().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static DnD.Player.PlayerOuterClass.Player parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static DnD.Player.PlayerOuterClass.Player parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static DnD.Player.PlayerOuterClass.Player parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static DnD.Player.PlayerOuterClass.Player parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static DnD.Player.PlayerOuterClass.Player parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static DnD.Player.PlayerOuterClass.Player parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static DnD.Player.PlayerOuterClass.Player parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static DnD.Player.PlayerOuterClass.Player parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static DnD.Player.PlayerOuterClass.Player parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static DnD.Player.PlayerOuterClass.Player parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static DnD.Player.PlayerOuterClass.Player parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static DnD.Player.PlayerOuterClass.Player parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(DnD.Player.PlayerOuterClass.Player prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code DnD.Player.Player}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:DnD.Player.Player)
        DnD.Player.PlayerOuterClass.PlayerOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return DnD.Player.PlayerOuterClass.internal_static_DnD_Player_Player_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return DnD.Player.PlayerOuterClass.internal_static_DnD_Player_Player_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                DnD.Player.PlayerOuterClass.Player.class, DnD.Player.PlayerOuterClass.Player.Builder.class);
      }

      // Construct using DnD.Player.PlayerOuterClass.Player.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        posX_ = 0F;

        posY_ = 0F;

        viewDistance_ = 0;

        currentTerrainPosX_ = 0F;

        currentTerrainPosY_ = 0F;

        if (terrainDataBuilder_ == null) {
          terrainData_ = null;
        } else {
          terrainData_ = null;
          terrainDataBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return DnD.Player.PlayerOuterClass.internal_static_DnD_Player_Player_descriptor;
      }

      @java.lang.Override
      public DnD.Player.PlayerOuterClass.Player getDefaultInstanceForType() {
        return DnD.Player.PlayerOuterClass.Player.getDefaultInstance();
      }

      @java.lang.Override
      public DnD.Player.PlayerOuterClass.Player build() {
        DnD.Player.PlayerOuterClass.Player result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public DnD.Player.PlayerOuterClass.Player buildPartial() {
        DnD.Player.PlayerOuterClass.Player result = new DnD.Player.PlayerOuterClass.Player(this);
        result.posX_ = posX_;
        result.posY_ = posY_;
        result.viewDistance_ = viewDistance_;
        result.currentTerrainPosX_ = currentTerrainPosX_;
        result.currentTerrainPosY_ = currentTerrainPosY_;
        if (terrainDataBuilder_ == null) {
          result.terrainData_ = terrainData_;
        } else {
          result.terrainData_ = terrainDataBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof DnD.Player.PlayerOuterClass.Player) {
          return mergeFrom((DnD.Player.PlayerOuterClass.Player)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(DnD.Player.PlayerOuterClass.Player other) {
        if (other == DnD.Player.PlayerOuterClass.Player.getDefaultInstance()) return this;
        if (other.getPosX() != 0F) {
          setPosX(other.getPosX());
        }
        if (other.getPosY() != 0F) {
          setPosY(other.getPosY());
        }
        if (other.getViewDistance() != 0) {
          setViewDistance(other.getViewDistance());
        }
        if (other.getCurrentTerrainPosX() != 0F) {
          setCurrentTerrainPosX(other.getCurrentTerrainPosX());
        }
        if (other.getCurrentTerrainPosY() != 0F) {
          setCurrentTerrainPosY(other.getCurrentTerrainPosY());
        }
        if (other.hasTerrainData()) {
          mergeTerrainData(other.getTerrainData());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        DnD.Player.PlayerOuterClass.Player parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (DnD.Player.PlayerOuterClass.Player) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private float posX_ ;
      /**
       * <code>float posX = 1;</code>
       * @return The posX.
       */
      public float getPosX() {
        return posX_;
      }
      /**
       * <code>float posX = 1;</code>
       * @param value The posX to set.
       * @return This builder for chaining.
       */
      public Builder setPosX(float value) {
        
        posX_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float posX = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearPosX() {
        
        posX_ = 0F;
        onChanged();
        return this;
      }

      private float posY_ ;
      /**
       * <code>float posY = 2;</code>
       * @return The posY.
       */
      public float getPosY() {
        return posY_;
      }
      /**
       * <code>float posY = 2;</code>
       * @param value The posY to set.
       * @return This builder for chaining.
       */
      public Builder setPosY(float value) {
        
        posY_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float posY = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearPosY() {
        
        posY_ = 0F;
        onChanged();
        return this;
      }

      private int viewDistance_ ;
      /**
       * <code>int32 viewDistance = 3;</code>
       * @return The viewDistance.
       */
      public int getViewDistance() {
        return viewDistance_;
      }
      /**
       * <code>int32 viewDistance = 3;</code>
       * @param value The viewDistance to set.
       * @return This builder for chaining.
       */
      public Builder setViewDistance(int value) {
        
        viewDistance_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 viewDistance = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearViewDistance() {
        
        viewDistance_ = 0;
        onChanged();
        return this;
      }

      private float currentTerrainPosX_ ;
      /**
       * <code>float currentTerrainPosX = 4;</code>
       * @return The currentTerrainPosX.
       */
      public float getCurrentTerrainPosX() {
        return currentTerrainPosX_;
      }
      /**
       * <code>float currentTerrainPosX = 4;</code>
       * @param value The currentTerrainPosX to set.
       * @return This builder for chaining.
       */
      public Builder setCurrentTerrainPosX(float value) {
        
        currentTerrainPosX_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float currentTerrainPosX = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearCurrentTerrainPosX() {
        
        currentTerrainPosX_ = 0F;
        onChanged();
        return this;
      }

      private float currentTerrainPosY_ ;
      /**
       * <code>float currentTerrainPosY = 5;</code>
       * @return The currentTerrainPosY.
       */
      public float getCurrentTerrainPosY() {
        return currentTerrainPosY_;
      }
      /**
       * <code>float currentTerrainPosY = 5;</code>
       * @param value The currentTerrainPosY to set.
       * @return This builder for chaining.
       */
      public Builder setCurrentTerrainPosY(float value) {
        
        currentTerrainPosY_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float currentTerrainPosY = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearCurrentTerrainPosY() {
        
        currentTerrainPosY_ = 0F;
        onChanged();
        return this;
      }

      private DnD.Player.PlayerOuterClass.TerrainData terrainData_;
      private com.google.protobuf.SingleFieldBuilderV3<
          DnD.Player.PlayerOuterClass.TerrainData, DnD.Player.PlayerOuterClass.TerrainData.Builder, DnD.Player.PlayerOuterClass.TerrainDataOrBuilder> terrainDataBuilder_;
      /**
       * <code>.DnD.Player.TerrainData terrainData = 6;</code>
       * @return Whether the terrainData field is set.
       */
      public boolean hasTerrainData() {
        return terrainDataBuilder_ != null || terrainData_ != null;
      }
      /**
       * <code>.DnD.Player.TerrainData terrainData = 6;</code>
       * @return The terrainData.
       */
      public DnD.Player.PlayerOuterClass.TerrainData getTerrainData() {
        if (terrainDataBuilder_ == null) {
          return terrainData_ == null ? DnD.Player.PlayerOuterClass.TerrainData.getDefaultInstance() : terrainData_;
        } else {
          return terrainDataBuilder_.getMessage();
        }
      }
      /**
       * <code>.DnD.Player.TerrainData terrainData = 6;</code>
       */
      public Builder setTerrainData(DnD.Player.PlayerOuterClass.TerrainData value) {
        if (terrainDataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          terrainData_ = value;
          onChanged();
        } else {
          terrainDataBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.DnD.Player.TerrainData terrainData = 6;</code>
       */
      public Builder setTerrainData(
          DnD.Player.PlayerOuterClass.TerrainData.Builder builderForValue) {
        if (terrainDataBuilder_ == null) {
          terrainData_ = builderForValue.build();
          onChanged();
        } else {
          terrainDataBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.DnD.Player.TerrainData terrainData = 6;</code>
       */
      public Builder mergeTerrainData(DnD.Player.PlayerOuterClass.TerrainData value) {
        if (terrainDataBuilder_ == null) {
          if (terrainData_ != null) {
            terrainData_ =
              DnD.Player.PlayerOuterClass.TerrainData.newBuilder(terrainData_).mergeFrom(value).buildPartial();
          } else {
            terrainData_ = value;
          }
          onChanged();
        } else {
          terrainDataBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.DnD.Player.TerrainData terrainData = 6;</code>
       */
      public Builder clearTerrainData() {
        if (terrainDataBuilder_ == null) {
          terrainData_ = null;
          onChanged();
        } else {
          terrainData_ = null;
          terrainDataBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.DnD.Player.TerrainData terrainData = 6;</code>
       */
      public DnD.Player.PlayerOuterClass.TerrainData.Builder getTerrainDataBuilder() {
        
        onChanged();
        return getTerrainDataFieldBuilder().getBuilder();
      }
      /**
       * <code>.DnD.Player.TerrainData terrainData = 6;</code>
       */
      public DnD.Player.PlayerOuterClass.TerrainDataOrBuilder getTerrainDataOrBuilder() {
        if (terrainDataBuilder_ != null) {
          return terrainDataBuilder_.getMessageOrBuilder();
        } else {
          return terrainData_ == null ?
              DnD.Player.PlayerOuterClass.TerrainData.getDefaultInstance() : terrainData_;
        }
      }
      /**
       * <code>.DnD.Player.TerrainData terrainData = 6;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          DnD.Player.PlayerOuterClass.TerrainData, DnD.Player.PlayerOuterClass.TerrainData.Builder, DnD.Player.PlayerOuterClass.TerrainDataOrBuilder> 
          getTerrainDataFieldBuilder() {
        if (terrainDataBuilder_ == null) {
          terrainDataBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              DnD.Player.PlayerOuterClass.TerrainData, DnD.Player.PlayerOuterClass.TerrainData.Builder, DnD.Player.PlayerOuterClass.TerrainDataOrBuilder>(
                  getTerrainData(),
                  getParentForChildren(),
                  isClean());
          terrainData_ = null;
        }
        return terrainDataBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:DnD.Player.Player)
    }

    // @@protoc_insertion_point(class_scope:DnD.Player.Player)
    private static final DnD.Player.PlayerOuterClass.Player DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new DnD.Player.PlayerOuterClass.Player();
    }

    public static DnD.Player.PlayerOuterClass.Player getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Player>
        PARSER = new com.google.protobuf.AbstractParser<Player>() {
      @java.lang.Override
      public Player parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Player(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Player> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Player> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public DnD.Player.PlayerOuterClass.Player getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface TerrainDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:DnD.Player.TerrainData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 existingTerrainCount = 1;</code>
     * @return The existingTerrainCount.
     */
    int getExistingTerrainCount();

    /**
     * <code>repeated float existingTerrainPositions = 2;</code>
     * @return A list containing the existingTerrainPositions.
     */
    java.util.List<java.lang.Float> getExistingTerrainPositionsList();
    /**
     * <code>repeated float existingTerrainPositions = 2;</code>
     * @return The count of existingTerrainPositions.
     */
    int getExistingTerrainPositionsCount();
    /**
     * <code>repeated float existingTerrainPositions = 2;</code>
     * @param index The index of the element to return.
     * @return The existingTerrainPositions at the given index.
     */
    float getExistingTerrainPositions(int index);
  }
  /**
   * Protobuf type {@code DnD.Player.TerrainData}
   */
  public  static final class TerrainData extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:DnD.Player.TerrainData)
      TerrainDataOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TerrainData.newBuilder() to construct.
    private TerrainData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TerrainData() {
      existingTerrainPositions_ = emptyFloatList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new TerrainData();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private TerrainData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              existingTerrainCount_ = input.readInt32();
              break;
            }
            case 21: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                existingTerrainPositions_ = newFloatList();
                mutable_bitField0_ |= 0x00000001;
              }
              existingTerrainPositions_.addFloat(input.readFloat());
              break;
            }
            case 18: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000001) != 0) && input.getBytesUntilLimit() > 0) {
                existingTerrainPositions_ = newFloatList();
                mutable_bitField0_ |= 0x00000001;
              }
              while (input.getBytesUntilLimit() > 0) {
                existingTerrainPositions_.addFloat(input.readFloat());
              }
              input.popLimit(limit);
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          existingTerrainPositions_.makeImmutable(); // C
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return DnD.Player.PlayerOuterClass.internal_static_DnD_Player_TerrainData_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return DnD.Player.PlayerOuterClass.internal_static_DnD_Player_TerrainData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              DnD.Player.PlayerOuterClass.TerrainData.class, DnD.Player.PlayerOuterClass.TerrainData.Builder.class);
    }

    public static final int EXISTINGTERRAINCOUNT_FIELD_NUMBER = 1;
    private int existingTerrainCount_;
    /**
     * <code>int32 existingTerrainCount = 1;</code>
     * @return The existingTerrainCount.
     */
    public int getExistingTerrainCount() {
      return existingTerrainCount_;
    }

    public static final int EXISTINGTERRAINPOSITIONS_FIELD_NUMBER = 2;
    private com.google.protobuf.Internal.FloatList existingTerrainPositions_;
    /**
     * <code>repeated float existingTerrainPositions = 2;</code>
     * @return A list containing the existingTerrainPositions.
     */
    public java.util.List<java.lang.Float>
        getExistingTerrainPositionsList() {
      return existingTerrainPositions_;
    }
    /**
     * <code>repeated float existingTerrainPositions = 2;</code>
     * @return The count of existingTerrainPositions.
     */
    public int getExistingTerrainPositionsCount() {
      return existingTerrainPositions_.size();
    }
    /**
     * <code>repeated float existingTerrainPositions = 2;</code>
     * @param index The index of the element to return.
     * @return The existingTerrainPositions at the given index.
     */
    public float getExistingTerrainPositions(int index) {
      return existingTerrainPositions_.getFloat(index);
    }
    private int existingTerrainPositionsMemoizedSerializedSize = -1;

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (existingTerrainCount_ != 0) {
        output.writeInt32(1, existingTerrainCount_);
      }
      if (getExistingTerrainPositionsList().size() > 0) {
        output.writeUInt32NoTag(18);
        output.writeUInt32NoTag(existingTerrainPositionsMemoizedSerializedSize);
      }
      for (int i = 0; i < existingTerrainPositions_.size(); i++) {
        output.writeFloatNoTag(existingTerrainPositions_.getFloat(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (existingTerrainCount_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, existingTerrainCount_);
      }
      {
        int dataSize = 0;
        dataSize = 4 * getExistingTerrainPositionsList().size();
        size += dataSize;
        if (!getExistingTerrainPositionsList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        existingTerrainPositionsMemoizedSerializedSize = dataSize;
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof DnD.Player.PlayerOuterClass.TerrainData)) {
        return super.equals(obj);
      }
      DnD.Player.PlayerOuterClass.TerrainData other = (DnD.Player.PlayerOuterClass.TerrainData) obj;

      if (getExistingTerrainCount()
          != other.getExistingTerrainCount()) return false;
      if (!getExistingTerrainPositionsList()
          .equals(other.getExistingTerrainPositionsList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + EXISTINGTERRAINCOUNT_FIELD_NUMBER;
      hash = (53 * hash) + getExistingTerrainCount();
      if (getExistingTerrainPositionsCount() > 0) {
        hash = (37 * hash) + EXISTINGTERRAINPOSITIONS_FIELD_NUMBER;
        hash = (53 * hash) + getExistingTerrainPositionsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static DnD.Player.PlayerOuterClass.TerrainData parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static DnD.Player.PlayerOuterClass.TerrainData parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static DnD.Player.PlayerOuterClass.TerrainData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static DnD.Player.PlayerOuterClass.TerrainData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static DnD.Player.PlayerOuterClass.TerrainData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static DnD.Player.PlayerOuterClass.TerrainData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static DnD.Player.PlayerOuterClass.TerrainData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static DnD.Player.PlayerOuterClass.TerrainData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static DnD.Player.PlayerOuterClass.TerrainData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static DnD.Player.PlayerOuterClass.TerrainData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static DnD.Player.PlayerOuterClass.TerrainData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static DnD.Player.PlayerOuterClass.TerrainData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(DnD.Player.PlayerOuterClass.TerrainData prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code DnD.Player.TerrainData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:DnD.Player.TerrainData)
        DnD.Player.PlayerOuterClass.TerrainDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return DnD.Player.PlayerOuterClass.internal_static_DnD_Player_TerrainData_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return DnD.Player.PlayerOuterClass.internal_static_DnD_Player_TerrainData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                DnD.Player.PlayerOuterClass.TerrainData.class, DnD.Player.PlayerOuterClass.TerrainData.Builder.class);
      }

      // Construct using DnD.Player.PlayerOuterClass.TerrainData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        existingTerrainCount_ = 0;

        existingTerrainPositions_ = emptyFloatList();
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return DnD.Player.PlayerOuterClass.internal_static_DnD_Player_TerrainData_descriptor;
      }

      @java.lang.Override
      public DnD.Player.PlayerOuterClass.TerrainData getDefaultInstanceForType() {
        return DnD.Player.PlayerOuterClass.TerrainData.getDefaultInstance();
      }

      @java.lang.Override
      public DnD.Player.PlayerOuterClass.TerrainData build() {
        DnD.Player.PlayerOuterClass.TerrainData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public DnD.Player.PlayerOuterClass.TerrainData buildPartial() {
        DnD.Player.PlayerOuterClass.TerrainData result = new DnD.Player.PlayerOuterClass.TerrainData(this);
        int from_bitField0_ = bitField0_;
        result.existingTerrainCount_ = existingTerrainCount_;
        if (((bitField0_ & 0x00000001) != 0)) {
          existingTerrainPositions_.makeImmutable();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.existingTerrainPositions_ = existingTerrainPositions_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof DnD.Player.PlayerOuterClass.TerrainData) {
          return mergeFrom((DnD.Player.PlayerOuterClass.TerrainData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(DnD.Player.PlayerOuterClass.TerrainData other) {
        if (other == DnD.Player.PlayerOuterClass.TerrainData.getDefaultInstance()) return this;
        if (other.getExistingTerrainCount() != 0) {
          setExistingTerrainCount(other.getExistingTerrainCount());
        }
        if (!other.existingTerrainPositions_.isEmpty()) {
          if (existingTerrainPositions_.isEmpty()) {
            existingTerrainPositions_ = other.existingTerrainPositions_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureExistingTerrainPositionsIsMutable();
            existingTerrainPositions_.addAll(other.existingTerrainPositions_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        DnD.Player.PlayerOuterClass.TerrainData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (DnD.Player.PlayerOuterClass.TerrainData) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int existingTerrainCount_ ;
      /**
       * <code>int32 existingTerrainCount = 1;</code>
       * @return The existingTerrainCount.
       */
      public int getExistingTerrainCount() {
        return existingTerrainCount_;
      }
      /**
       * <code>int32 existingTerrainCount = 1;</code>
       * @param value The existingTerrainCount to set.
       * @return This builder for chaining.
       */
      public Builder setExistingTerrainCount(int value) {
        
        existingTerrainCount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 existingTerrainCount = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearExistingTerrainCount() {
        
        existingTerrainCount_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.Internal.FloatList existingTerrainPositions_ = emptyFloatList();
      private void ensureExistingTerrainPositionsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          existingTerrainPositions_ = mutableCopy(existingTerrainPositions_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated float existingTerrainPositions = 2;</code>
       * @return A list containing the existingTerrainPositions.
       */
      public java.util.List<java.lang.Float>
          getExistingTerrainPositionsList() {
        return ((bitField0_ & 0x00000001) != 0) ?
                 java.util.Collections.unmodifiableList(existingTerrainPositions_) : existingTerrainPositions_;
      }
      /**
       * <code>repeated float existingTerrainPositions = 2;</code>
       * @return The count of existingTerrainPositions.
       */
      public int getExistingTerrainPositionsCount() {
        return existingTerrainPositions_.size();
      }
      /**
       * <code>repeated float existingTerrainPositions = 2;</code>
       * @param index The index of the element to return.
       * @return The existingTerrainPositions at the given index.
       */
      public float getExistingTerrainPositions(int index) {
        return existingTerrainPositions_.getFloat(index);
      }
      /**
       * <code>repeated float existingTerrainPositions = 2;</code>
       * @param index The index to set the value at.
       * @param value The existingTerrainPositions to set.
       * @return This builder for chaining.
       */
      public Builder setExistingTerrainPositions(
          int index, float value) {
        ensureExistingTerrainPositionsIsMutable();
        existingTerrainPositions_.setFloat(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated float existingTerrainPositions = 2;</code>
       * @param value The existingTerrainPositions to add.
       * @return This builder for chaining.
       */
      public Builder addExistingTerrainPositions(float value) {
        ensureExistingTerrainPositionsIsMutable();
        existingTerrainPositions_.addFloat(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated float existingTerrainPositions = 2;</code>
       * @param values The existingTerrainPositions to add.
       * @return This builder for chaining.
       */
      public Builder addAllExistingTerrainPositions(
          java.lang.Iterable<? extends java.lang.Float> values) {
        ensureExistingTerrainPositionsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, existingTerrainPositions_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated float existingTerrainPositions = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearExistingTerrainPositions() {
        existingTerrainPositions_ = emptyFloatList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:DnD.Player.TerrainData)
    }

    // @@protoc_insertion_point(class_scope:DnD.Player.TerrainData)
    private static final DnD.Player.PlayerOuterClass.TerrainData DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new DnD.Player.PlayerOuterClass.TerrainData();
    }

    public static DnD.Player.PlayerOuterClass.TerrainData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TerrainData>
        PARSER = new com.google.protobuf.AbstractParser<TerrainData>() {
      @java.lang.Override
      public TerrainData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TerrainData(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TerrainData> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TerrainData> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public DnD.Player.PlayerOuterClass.TerrainData getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DnD_Player_Player_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DnD_Player_Player_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DnD_Player_TerrainData_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DnD_Player_TerrainData_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014Player.proto\022\nDnD.Player\"\240\001\n\006Player\022\014\n" +
      "\004posX\030\001 \001(\002\022\014\n\004posY\030\002 \001(\002\022\024\n\014viewDistanc" +
      "e\030\003 \001(\005\022\032\n\022currentTerrainPosX\030\004 \001(\002\022\032\n\022c" +
      "urrentTerrainPosY\030\005 \001(\002\022,\n\013terrainData\030\006" +
      " \001(\0132\027.DnD.Player.TerrainData\"M\n\013Terrain" +
      "Data\022\034\n\024existingTerrainCount\030\001 \001(\005\022 \n\030ex" +
      "istingTerrainPositions\030\002 \003(\002B\036\n\nDnD.Play" +
      "erB\020PlayerOuterClassb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_DnD_Player_Player_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_DnD_Player_Player_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DnD_Player_Player_descriptor,
        new java.lang.String[] { "PosX", "PosY", "ViewDistance", "CurrentTerrainPosX", "CurrentTerrainPosY", "TerrainData", });
    internal_static_DnD_Player_TerrainData_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_DnD_Player_TerrainData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DnD_Player_TerrainData_descriptor,
        new java.lang.String[] { "ExistingTerrainCount", "ExistingTerrainPositions", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
